feat: get deleted products and categories
7-Seven-Up/megastore-backend pull request #124
Opened 2024-11-29 22:16 UTC by delgadomatias

Ahora existe un endpoint para obtener los productos y las categorías eliminadas. 

Con respecto a los productos, cambié un par de cosas:
- La respuesta del ProductResponse, agregué atributos como _hasVariants_ y _variantOfName_, ya que son importantes en el frontend para mostrar información y para ofrecer una mejor experiencia de usuario a la hora de querer eliminar un producto: al tener el _hasVariants_ podemos habilitar/deshabilitar el botón de eliminar producto como más nos convenga.
- Opté por mostrar todos los productos, es decir, el super producto y sus variantes. Ya que como administrador en el panel necesito ver todos y no solo los super productos, creo que esto es lo más fácil y rápido que podemos hacer.

2024-11-29 22:35 UTC, EzeSosa requested changes
Lo veo a todo re bien, pero habría que agregar estos endpoints en la configuración de seguridad para que después no se nos rompa todo jajajaja

2024-11-29 23:04 UTC, Fedesan14 approved these changes
Te dejo un par de comentarios, dejo a tu decision si te parece bien o no hacer el cambio. Es una cuestion de diseño de los endpoints nomas, por ahi a lo mejor te conviene tenerlo separados asi que te lo apruebo de todas formas

2024-11-29 23:04 UTC, Fedesan14 commented on src/main/java/com/_up/megastore/data/repositories/ICategoryRepository.java
> +    Page<Category> findCategoriesByDeletedIsTrue(Pageable pageable);
Teniendo en cuenta los comentarios de recien, este metodo no se generaria y podriamos reutilizar el que teniamos previamente cambiandolo un poquito

```
 Page<Category> findCategoryByDeletedAndNameContainingIgnoreCase(boolean deleted, String name, Pageable pageable);
```

2024-11-29 23:04 UTC, Fedesan14 commented on src/main/java/com/_up/megastore/data/repositories/IProductRepository.java
> +        Pageable pageable);
Mismo comentario que recien

```suggestion
    Page<Product> findProductsByDeletedAndNameContainingIgnoreCase(boolean deleted, String name,
        Pageable pageable);
```

2024-11-29 23:04 UTC, Fedesan14 commented on src/main/java/com/_up/megastore/services/implementations/CategoryService.java
> +    }
Este metodo se iria y podriamos reutilizar el mismo que teniamos antes, ya que segun el parametro "deleted" te va a retornar los que estan eliminados o no

2024-11-30 15:27 UTC, delgadomatias commented
@Fedesan14 pero no sería posible proteger ese endpoint, la idea es que solo los administradores puedan ver los productos eliminados

2024-11-30 16:03 UTC, Fedesan14 commented
> @Fedesan14 pero no sería posible proteger ese endpoint, la idea es que solo los administradores puedan ver los productos eliminados

Definiendo el path como /products** o /products* no te acepta los query params? Veria raro que no haya forma de hacer que no tenga en cuenta los queryParams para la seguridad

2024-11-30 16:11 UTC, Fedesan14 commented
Bueno estuve viendo un poco y es un bardo hacer que detecte los query params, asi que lo dejemos en dos endpoints distintos

2024-11-30 19:20 UTC, delgadomatias commented
@EzeSosa no sabría como hacer para que solo los administradores puedan acceder a estos endpoints, de hecho ya existen en una constante y con el hasRole se las está validando, pero no funciona. Si tenes ganas de ver que onda lo hacemos si no lo dejamos, no perdamos tiempo ya en estas cosas

2024-11-30 21:58 UTC, merged