Feat/update product
7-Seven-Up/megastore-backend pull request #20
Opened 2024-08-31 16:51 UTC by martinjcrosetto

New feature for update details of a product, allowing users to modify: name, description, image, category, subcategory
Changes Made:

- UpdateProductRequest
 
- IProductController
- ProductController

- IProductService
- ProductService

- ProductMapper

2024-08-31 17:43 UTC, Fedesan14 requested changes
Te dejo algunos cambios de errores que te deberian saltar en la compilación al momento de levantar el proyecto... lo que me hace pensar que no levantaste el proyecto, ¿probaste que los cambios funcionaran correctamente?

2024-08-31 17:43 UTC, Fedesan14 commented on src/main/java/com/_up/megastore/controllers/interfaces/IProductController.java
> +            @RequestPart @Valid UpdateProductRequest updateProductRequest,
Esto debería ser un RequestBody mas que RequestPart

```suggestion
            @RequestBody @Valid UpdateProductRequest updateProductRequest,
```

2024-08-31 17:43 UTC, Fedesan14 commented on src/main/java/com/_up/megastore/controllers/implementations/ProductController.java
> +    }
Acá se supone que estás implementando el método que definiste en la interfas IProductController, pero no coinciden los parámetros qeu definis en la interfaz, esto incluso te debería dar error.

Además, estás llamando al método updateProduct del productService pasándole el tipo de dato de los parámetros. Cuando llamás a un método solo tenes que pasarle el parámetro, no el tipo de dato

```suggestion
    @Override
    public ProductResponse updateProduct(UpdateProductRequest updateProductRequest, MultipartFile multipartFile){
       return productService.updateProduct(updateProductRequest, multipartFile);

    }
```

2024-08-31 17:43 UTC, Fedesan14 commented on src/main/java/com/_up/megastore/services/implementations/ProductService.java
> +        Category category = categoryService.findCategoryByIdOrThrowException(UpdateProductRequest.categoryId());
Acá estás queriendo usar el categoryId que te llega de la request, pero el orden en el que se definen las cosas en el método es

<TipoDeAcceso> <TipoDeRetorno> <nombreMetodo> (TipoDeVariable nombreVariable) {}

por lo tanto, deberias usar updateProductRequest en vez de UpdateProductRequest

```suggestion
        Category category = categoryService.findCategoryByIdOrThrowException(updateProductRequest.categoryId());
```

2024-08-31 17:48 UTC, EzeSosa requested changes
Para la próxima fijate bien que compile y probá haciendo algunas pruebas en Postman (también lo vemos después si no sabés usarlo). Probá con estos cambios y cualquier cosa avisá. No te desmotives

2024-08-31 17:48 UTC, EzeSosa commented on src/main/java/com/_up/megastore/controllers/requests/UpdateProductRequest.java
> +)
Acá faltan las llaves de apertura y cierre ({}). Si no las ponés el código no compila

2024-08-31 17:48 UTC, EzeSosa commented on src/main/java/com/_up/megastore/services/implementations/ProductService.java
> +    }
Acá estás haciendo exactamente lo mismo que se hace en el saveProduct, es decir, estarías creando un nuevo producto.

Para actualizar un producto, los pasos que deberías seguir son:

1. Obtener el producto a actualizar -- ya debe existir en la base de datos!
2. Actualizar los campos (podés utilizar los _setters_)
3. Guardar el producto actualizado
4. Devolver el DTO del producto actualizado

Si tenés inconvenientes o no me entendiste después lo vemos

2024-08-31 17:48 UTC, EzeSosa commented on src/main/java/com/_up/megastore/services/interfaces/IProductService.java
> +    ProductResponse updateProduct(UpdateProductRequest updateProductRequest, MultipartFile multipartFile);
Acá falta un atributo importante: la ID del producto actualizar. Siguiendo el comentario anterior, la manera en la que deberías obtener el producto ya existente en la base de datos es a través de su ID.

El método debería quedar así:

```suggestion
    ProductResponse updateProduct(UUID productId, UpdateProductRequest updateProductRequest, MultipartFile multipartFile);
```

2024-08-31 17:48 UTC, EzeSosa commented on src/main/java/com/_up/megastore/services/mappers/ProductMapper.java
> +    @Override
El Override sólo se utiliza para **sobreescribir** un método. En este caso, ProductMapper no extiende ni implementa ninguna otra clase por lo que el @Override está de más.

2024-08-31 17:48 UTC, EzeSosa commented on src/main/java/com/_up/megastore/services/mappers/ProductMapper.java
> +    }
Esto está de más. Como te dije antes, podrías buscar el producto por su ID para obtener el producto directamente y no tener que construirlo vos mismo.

2024-08-31 17:48 UTC, EzeSosa commented on src/main/java/com/_up/megastore/controllers/interfaces/IProductController.java
> +    );
Acá falta el parámetro con la ID del producto. La ruta está bien, puesto que vas a hacerle la petición a api/v1/products/id-del-producto. Ahora, ese ID tiene que recibirse en el método como una variable.

Debería quedarte así:

```suggestion
    @PatchMapping(value = "/{productId}", consumes = { MediaType.MULTIPART_FORM_DATA_VALUE, MediaType.APPLICATION_JSON_VALUE })
    @ResponseStatus(HttpStatus.OK)
    ProductResponse updateProduct(
            @PathVariable UUID productId,
            @RequestPart @Valid UpdateProductRequest updateProductRequest,
            @RequestPart MultipartFile multipartFile
    );
```

2024-08-31 17:48 UTC, EzeSosa commented on src/main/java/com/_up/megastore/controllers/implementations/ProductController.java
> +import com._up.megastore.services.implementations.ProductService;
Tratemos de evitar los imports no utilizados (en tu IDE deberían mostrarse en color gris)

2024-08-31 17:48 UTC, EzeSosa commented on src/main/java/com/_up/megastore/controllers/implementations/ProductController.java
> +import org.springframework.web.bind.annotation.PutMapping;
Acá hay otro import no utilizado

2024-08-31 17:48 UTC, EzeSosa commented on src/main/java/com/_up/megastore/controllers/requests/UpdateProductRequest.java
> +    UUID variantOfId
Sobre esto, yo dejaría para actualizar únicamente el nombre, la descripción, el precio, el stock y el color (faltaron el stock y el color).

2024-08-31 18:16 UTC, martinjcrosetto commented on src/main/java/com/_up/megastore/controllers/requests/UpdateProductRequest.java
> +    UUID variantOfId
![image](https://github.com/user-attachments/assets/e1ed51fa-fd93-4d0d-8f48-488db3433aef)

2024-08-31 18:17 UTC, martinjcrosetto commented on src/main/java/com/_up/megastore/controllers/requests/UpdateProductRequest.java
> +    UUID variantOfId
Esto quiere decir que no tengo en cuenta foto, categoría y subcategoría

2024-08-31 19:01 UTC, EzeSosa commented on src/main/java/com/_up/megastore/controllers/requests/UpdateProductRequest.java
> +    UUID variantOfId
Ah está bien, no había leído esa parte. Podés dejarlo como está

2024-09-01 00:16 UTC, EzeSosa requested changes
Fijate si podés solucionar la de variantOf. Otra cosa, si podés evitar las dobles líneas vacías mejor

2024-09-01 00:16 UTC, EzeSosa commented on src/main/java/com/_up/megastore/services/implementations/ProductService.java
> +    public ProductResponse updateProduct(UUID productId, UpdateProductRequest updateProductRequest, MultipartFile multipartFile){
Sé que no es necesario, pero ya que vas a hacer un commit para eliminar los setters podrías agregarle a este método el @Override para que quede explícito que está definido en la interfaz (los métodos del save también tienen esta anotación).

2024-09-01 00:16 UTC, EzeSosa commented on src/main/java/com/_up/megastore/services/implementations/ProductService.java
> +        Product variantOf = this.getVariantOf(updateProductRequest.variantOfId());
La idea está bien, pero hay un problema. En el UpdateProductRequest el 'variantOfId' no está validado por jakarta. Esto significa que el usuario puede incluirlo o no (si desea sobreescribir la variante o no).

Imaginate, entonces, que un usuario hace un update sin especificar el variantOfId (o escribiéndolo mal). Lo que va a pasar es que el producto, que antes apuntaba a otro producto, ahora va a pasar a ser _null_. Esto no debería ocurrir, sino que la variante debería ser exactamente la misma. Lo que sugeriría yo es agregar la siguiente validación:

```suggestion
    if (updateProductRequest.variantOfId() != null) {
        Product variantOf = this.getVariantOf(updateProductRequest.variantOfId());
        product.setVariantOf(variantOf);
    }
```
Que podría extraerse a su propio método quizás (ifVariantOfIdExistsUpdateProductVariantOf). Esto mismo podría aplicarse al Category si sacamos la validación @NotNull en la request.

2024-09-01 23:17 UTC, EzeSosa requested changes
Tu PR casi está lista. Parecen una pavada las correcciones pero la estética también es importante y hace a la legibilidad del código (y además no cuesta nada)

2024-09-01 23:17 UTC, EzeSosa commented on src/main/java/com/_up/megastore/controllers/interfaces/IProductController.java
> +            @RequestPart @Valid UpdateProductRequest updateProductRequest,
Esto está bien para este caso. Acá se pone RequestPart porque dividimos la request en dos partes: una para la imagen y otra para el JSON con la request. Si se pone RequestBody y RequestPart va a devolver un 415

2024-09-01 23:17 UTC, EzeSosa commented on src/main/java/com/_up/megastore/services/implementations/ProductService.java
>      public ProductResponse updateProduct(UUID productId, UpdateProductRequest updateProductRequest, MultipartFile multipartFile){
¿Por qué tantas líneas vacías? Podrías dejarlo así

```suggestion
    @Override
    public ProductResponse updateProduct(UUID productId, UpdateProductRequest updateProductRequest, MultipartFile multipartFile) {
```
Es importante que el código quede legible

2024-09-01 23:17 UTC, EzeSosa commented on src/main/java/com/_up/megastore/services/implementations/ProductService.java
>      }
La lógica está bien pero, de nuevo, los espacios. Deberíamos respetar el formato del código en todas las clases

```suggestion
    }
    public void ifVariantOfExistsUpdateProductVariantOf(UpdateProductRequest updateProductRequest, Product product) {
        if(updateProductRequest.variantOfId() != null) {
            Product variantOf = this.getVariantOf(updateProductRequest.variantOfId());
            product.setVariantOf(variantOf);
        }
    }
    
    public void ifImageURLExistsUpdateProductImageURL(MultipartFile multipartFile, Product product) {
        if (saveProductImage(multipartFile) != null) {
            String imageURL = saveProductImage(multipartFile);
            product.setImageURL(imageURL);
        }
    }
```
Los métodos tienen que separarse entre sí por una sola línea, sino nos queda todo junto

2024-09-01 23:22 UTC, Fedesan14 commented on src/main/java/com/_up/megastore/controllers/requests/UpdateProductRequest.java
> +    UUID variantOfId
Si el comentario está resuelto @EzeSosa  @martinjcrosetto , cerremoslo para que no quede abierto en los proximos reviews

2024-09-01 23:51 UTC, Fedesan14 requested changes
Dejo algunos comentarios, lo estoy viendo bastante bien dentro de todo =) Cuando se suban los cambios y se discutan algunas cosas que dejé lo reviso de nuevo y vamos viendo como progresa el MR

2024-09-01 23:51 UTC, Fedesan14 commented on src/main/java/com/_up/megastore/services/implementations/ProductService.java
> +    public ProductResponse updateProduct(UUID productId, UpdateProductRequest updateProductRequest, MultipartFile multipartFile){
No te va a dar un error, pero se ponen las etiquetas justamente previo a lo que se desea aplicarle ese label

```suggestion
    @Override
    public ProductResponse updateProduct(UUID productId, UpdateProductRequest updateProductRequest, MultipartFile multipartFile){
```

2024-09-01 23:51 UTC, Fedesan14 commented on src/main/java/com/_up/megastore/services/implementations/ProductService.java
> +    }
Ojo que no es del todo correcto esto, todo depende de la experiencia de usuario que se desea. El save de JpaRepository te permite crear una entidad o actualizar una ya existente sin necesidad de buscarla previamente

1. Si el ID no existe, lo crea
2. Si el ID existe, lo actualiza con los datos de la entity que nosotros le pasemos. 

Es una cuestión de experiencia de usuario o de manejo de errores del backend previamente buscar la entidad y si no existe, tirar un error

2024-09-01 23:51 UTC, Fedesan14 commented on src/main/java/com/_up/megastore/services/implementations/ProductService.java
> +    }
Que pasa si el variantOf viene como null? No sería correcto decir que se actualiza para un producto deje de ser una variante de tal cosa? Es algo para discutir nomás

2024-09-01 23:51 UTC, Fedesan14 commented on src/main/java/com/_up/megastore/services/implementations/ProductService.java
> +    }
¿No se puede quitar una imagen del producto? Si o si tiene que tener una asociada?

2024-09-01 23:51 UTC, Fedesan14 commented on src/main/java/com/_up/megastore/services/implementations/ProductService.java
> +    }
Dejo como alternativa para pensar, el utilizar una imagen por default que se puede usar cuando no se desea agregar la imagen a un producto

2024-09-02 14:16 UTC, EzeSosa approved these changes
Banco. Lo de las imágenes por defecto lo podemos agregar en otra feature. Esperemos a que Fede revise y mergee

2024-09-02 14:20 UTC, EzeSosa commented on src/main/java/com/_up/megastore/services/implementations/ProductService.java
> +    }
Sobre esto, estoy de acuerdo. Podríamos agregar una imagen por defecto para los productos que no la tengan en una nueva feature

2024-09-02 14:21 UTC, EzeSosa commented on src/main/java/com/_up/megastore/services/implementations/ProductService.java
> +    }
A esto no lo corregí porque no se me ocurre ningún caso en el que se pueda actualizar un producto para que deje de ser variante de otro. Normalmente las variantes cambian el color o algún que otro atributo mínimo pero es raro que dejen de ser variantes de otros debido a su naturaleza

2024-09-03 01:19 UTC, Fedesan14 approved these changes
Buen laburo Crous, apruebo y mergeo

2024-09-03 01:19 UTC, merged