Consultar Producto
7-Seven-Up/megastore-backend pull request #21
Opened 2024-08-31 17:48 UTC by ValeLattanzi

Se agregaron dos endpoints al controlador de producto:

1. Consulta de un producto en particular por ID.
2. Consulta de productos por paginación.

2024-09-01 00:32 UTC, EzeSosa requested changes
Muy bien lo de la paginación. Podrías implementar el sortBy si querés hacerlo. Lo importante es lo de la flag 'deleted'

2024-09-01 00:32 UTC, EzeSosa commented on src/main/java/com/_up/megastore/services/implementations/ProductService.java
> +        Product product = productRepository.findById(productId).orElseThrow(NoSuchElementException::new);
Acá estamos repitiendo código, podrías haber usado el findProductByIdOrThrowException en vez de llamar nuevamente al repositorio y tirar otra excepción

2024-09-01 00:32 UTC, EzeSosa commented on src/main/java/com/_up/megastore/services/mappers/ProductMapper.java
> +@Component
Esto no hace falta porque los métodos del mapper son estáticos, estamos agregando un bean innecesario al contenedor

2024-09-01 00:32 UTC, EzeSosa commented on src/main/java/com/_up/megastore/controllers/interfaces/IProductController.java
> +    );
Excelente la paginación. Si tenés ganas podrías implementar lo del sortBy. Está bueno

2024-09-01 00:32 UTC, EzeSosa commented on src/main/java/com/_up/megastore/services/implementations/ProductService.java
>      }
La lógica está bien pero habría que reescribir el findAll debido a que en nuestra entity tenemos la flag 'deleted' para hacer el delete lógico. Entonces, aquellos objetos cuyo 'deleted' sea true no deberían mostrarse puesto que, si bien están presentes en la base de datos, están eliminados por el usuario.

Para hacer eso podrías usar un Query Method: https://www.baeldung.com/spring-data-derived-queries

2024-09-01 00:32 UTC, EzeSosa commented on src/main/java/com/_up/megastore/services/implementations/ProductService.java
> +        return productRepository.findById(productId).orElseThrow(() -> new NoSuchElementException("Product with id " + productId + " does not exist."));
Este findById del repositorio también debería sobreescribirse para que, si está 'eliminado', no mostrarse.

```suggestion
        return productRepository.findByIdAndDeletedFalse(productId).orElseThrow(() -> new NoSuchElementException("Product with id " + productId + " does not exist."));
```

2024-09-01 00:32 UTC, EzeSosa commented on src/main/java/com/_up/megastore/controllers/implementations/ProductController.java
> +    public ProductResponse findProductById(@PathVariable UUID id) {
El @PathVariable está de más (no afecta la lógica pero la anotación ya está en la interfaz)

2024-09-01 18:37 UTC, EzeSosa commented on src/main/java/com/_up/megastore/controllers/interfaces/IProductController.java
> +            @RequestParam(defaultValue = "name") String sortBy
Excelente el uso de los default values

2024-09-01 18:37 UTC, EzeSosa commented on src/main/java/com/_up/megastore/data/repositories/IProductRepository.java
> +public interface IProductRepository extends JpaRepository<Product, UUID>, JpaSpecificationExecutor<Product> {
Acá probé quitando la extensión a JpaSpecificationExecutor y funcionó igual. El JPA Repository por defecto proporciona soporte a los query methods si están escritos en el formato correcto (en este caso sí lo están). Creo que podría eliminarse

2024-09-01 18:37 UTC, EzeSosa commented on src/main/java/com/_up/megastore/services/implementations/ProductService.java
> +import java.util.*;
Parece una pavada pero estaría bueno evitar los imports masivos (java.util.*) porque hacen la ejecución más lenta de lo que ya es. Si estás usando IntelliJ esto puede evitarse con una configuración

2024-09-01 20:30 UTC, Fedesan14 requested changes
Te dejo algunos comentarios que vi por ahora, caundo hagas los cambios lo reviso de nuevo

2024-09-01 20:30 UTC, Fedesan14 commented on src/main/java/com/_up/megastore/data/repositories/IProductRepository.java
> +    Page<Product> findProductsByDeletedIsFalseAndNameLikeIgnoreCase(String filter, Pageable pageable);
Por lo que entiendo es que la query se realiza por el nombre del producto, en ese caso en vez de "filter" pondria "name" como parametro para que se entienda cual es el tipo de filtro (esto tanto en los controller como en el service

Si queda como filter es muy generico y no se sabria por cual de todos los datos del producto se va a filtrar

2024-09-01 20:30 UTC, Fedesan14 commented on src/main/java/com/_up/megastore/controllers/interfaces/IProductController.java
> +            @RequestParam(defaultValue = "") String filter
Siguiendo el comentario anterior, aca deberia cambiarse a name

```suggestion
            @RequestParam(defaultValue = "") String name
```

2024-09-01 20:30 UTC, Fedesan14 commented on src/main/java/com/_up/megastore/controllers/interfaces/IProductController.java
> +    Page<ProductResponse> findProductsByPages(
Aca no hace falta que agreguemos el sufijo "ByPages" porque si bien obtenemos una pagina en particular, no estamos buscando los productos por pagina especificamente, solo es una técnica para evitar la obtención de muchos datos en la base de datos, yo lo dejaría así nomas

```suggestion
    Page<ProductResponse> findProducts(
```

2024-09-01 20:30 UTC, Fedesan14 commented on src/main/java/com/_up/megastore/controllers/interfaces/IProductController.java
> +    Page<ProductResponse> findProductsByPages(
Incluso, es mejor que especifiquemos el "byName" porque sí es un filtro por el cual vamos a estar buscando los productos (no lo agregaria tampoco ya que es opcional)

2024-09-01 20:30 UTC, Fedesan14 commented on src/main/java/com/_up/megastore/services/implementations/ProductService.java
> +    }
Acá nos podemos evitar guardar en memoria un producto si combinamos los métodos

```suggestion
    public ProductResponse getProduct(UUID productId) {
        return ProductMapper.toProductResponse(
            findProductByIdOrThrowException(productId)
        );
    }
```

2024-09-01 20:30 UTC, Fedesan14 commented on src/main/java/com/_up/megastore/services/implementations/ProductService.java
> +        Pageable pageable = PageRequest.of(page, pageSize, sort);
Podriamos recibir tambien por parametro el tipo de dirección y agregarlo en este PageRequest el cual nos permite devolver los datos en orden Ascendente o descendente, lo dejo a tu criterio si te parece bien

2024-09-01 20:30 UTC, Fedesan14 commented on src/main/java/com/_up/megastore/services/implementations/ProductService.java
> +                .map(ProductMapper::toProductResponse);
Entiendo que la concatenacion de los % es para buscar coincidencias por el nombre... Esto es porque estás usando el Like en el repositorio, probá el containing

```suggestion
        return productRepository.findProductsByDeletedIsFalseAndNameContainingIgnoreCase(filter, pageable)
                .map(ProductMapper::toProductResponse);
```

2024-09-02 22:52 UTC, EzeSosa requested changes
Agrego una corrección más a lo de Fede, total vas a poder implementarlo dentro de los otros commits

2024-09-02 22:52 UTC, EzeSosa commented on src/main/java/com/_up/megastore/data/repositories/IProductRepository.java
> +import java.util.*;
Habría que evitar los imports generales, sobre todo para librerías tan amplias como java.util. A esto lo podés configurar en tu IntelliJ

2024-09-03 01:25 UTC, Fedesan14 commented
@ValeLattanzi se mergearon algunas cosas a main lo que está generando conflictos con tus cambios, además, hay algunos comentarios que hizo @EzeSosa que todavía no se cambiaron (tiene que ver con los imports). Y porfa, cerremos los comentarios una vez que se commitea si se hicieron los cambios correspondientes, esto por ejemplo ya se hicieron los cambios pero no se cerró el comentario, y como este hay varios otros

![image](https://github.com/user-attachments/assets/960d543f-4f69-4975-aaea-d6a2078124ff)

2024-09-03 14:05 UTC, ValeLattanzi commented on src/main/java/com/_up/megastore/services/implementations/ProductService.java
> +        Pageable pageable = PageRequest.of(page, pageSize, sort);
Creo que eso se puede resolver en el front, total con la paginacion no es mucho ordenar un bloque de 30 objetos como mucho

2024-09-05 20:22 UTC, Fedesan14 requested changes
Despues de nivelarte con main, se agregaron cambios que no deberían aparecer en tu MR, de hecho si te fijas, en los archivos que cambiaste figuran cosas como updateProduct, updateSize, cosas que no deberías haber tocado, incluso estas elimiando un método de la interfaz IProductService cuando no debería ser responsabilidad en este MR. 

Esto debe ser porque cuando quisiste nivelar en vez de "juntar" los codigos, lo armaste manualmente y esto está mal porque es como si vos hicieras cambios sobre eso (aunque sigue siendo lo mismo). Habría que deshacer los últimos cambios y volver a nivelar con main, si querés para resolver estos conflictos pedile ayuda a @EzeSosa o a mi cuando puedas y lo vemos juntos

2024-09-07 15:19 UTC, closed without merging