feat/update size
7-Seven-Up/megastore-backend pull request #24
Opened 2024-09-01 21:51 UTC by martinjcrosetto

New feature for update details of a size, allowing users to modify: name and description
Changes Made:

UpdateSizeRequest

ISizeController

SizeController

ISizeService

SizeService

2024-09-01 23:20 UTC, Fedesan14 requested changes
Te dejo comentado un cambio para hacer

2024-09-01 23:20 UTC, Fedesan14 commented on src/main/java/com/_up/megastore/controllers/requests/UpdateSizeRequest.java
> +        @NotNull(message = "Size name must not be null")
Esta etiqueta NotNull valida que si o si se envíe el nombre, pero puede enviarse una cadena vacío y lo toma como valido (el cual no es correcto).

Para esta validación extra existe una etiqueta llamada NotBlank el que además de verificar que se envíe (que no sea null) verifica que no sea una calida vacía.

```suggestion
        @NotBlank(message = "Size name must not be null")
```

2024-09-01 23:20 UTC, Fedesan14 commented on src/main/java/com/_up/megastore/controllers/requests/UpdateSizeRequest.java
> +        @NotNull(message = "Size description must not be null")
En este caso, me parece correcto que una descripción pueda ser vacía, lo dejo a criterio de ustedes si esto lo pasamos a NotBlank o lo dejamos como NotNull

2024-09-02 14:18 UTC, EzeSosa approved these changes

2024-09-03 01:21 UTC, Fedesan14 approved these changes
Apruebo y mergeo

![image](https://github.com/user-attachments/assets/19787a37-d1c9-4b8b-a326-4f55b6185357)

2024-09-03 01:21 UTC, merged