feat/register-users
7-Seven-Up/megastore-backend pull request #25
Opened 2024-09-02 01:28 UTC by delgadomatias

Implementación del registro de usuarios; guardando la contraseña codificada y enviando un correo de bienvenida.
 # Importante
Necesite instalar Spring Security y realizar una configuración básica que me permita acceder a todas las rutas.

Con respecto al campo **phoneNumber**, decidí instalar una librería de Google que valida un número dado un código de país (**se debe registrar el numero con el código de área).** Además, cree un método en la entidad User para guardar el número en un formato estandarizado (E.164).  Para hacer la validación en el DTO opte por la creación de un custom constraint (**PhoneNumberConstraint**)

2024-09-02 02:35 UTC, Fedesan14 requested changes
Dejo algunos comentarios pero tengo más cosas para agregar respecto a la PR:

1. Segun la historia de usuario no debería haberse agregado seguridad a los endpoints por lo que no entiendo la razón de haber agregado spring-security (aunque en un futuro vamos a tener que hacerlo)
2. El usuario tiene que confirmar la creación de la cuenta mediante el uso del mail, pero el mail que le estamos enviando solo le da una bienvenida, pero no le mandamos ningun link de confirmación o algo por el estilo, por lo que deberíamos generar una lógica que haga eso mismo, habría que diseñar bien una solución de cómo hacerlo, en lo personal nunca lo hice así que sería un buen desafío si quieren que nos juntemos todo para hacerlo, de paso arrobo a los demás por este punto @martinjcrosetto @EzeSosa @ValeLattanzi

2024-09-02 02:35 UTC, Fedesan14 commented on src/main/java/com/_up/megastore/services/interfaces/IMailSenderService.java
> +  void sendWelcomeEmail(User user);
Muy bien el uso de asincronismo para enviar los emails =)

2024-09-02 02:35 UTC, Fedesan14 commented on src/main/resources/application.yaml
> +    password: ${MAIL_PASSWORD:kemb pmbj helh ikvn}
Ojo con estos valores por defectos que estás seteando ya que solo serviría en un ambiente de desarrollo, si el día de mañana esto se hosteara en un ambiente productivo y por alguna razon no se setean las variables, Spring va a tomar los valores que vos definiste por defecto acá lo cual estaría mal. Para evitar esto podes usar el application-development.yaml definiendo las mismas propiedades con los valores que estás definiendo por defecto acá, este archivo entonces te quedaría como

```suggestion
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
```

Pero a su vez tendrias el application-development.yaml así 

```
  mail:
    host: smtp.gmail.com
    port: 587}
    username: 7up.megastore@gmail.com
    password: kemb pmbj helh ikvn
```

De esta forma cuando levantas el proyecto en modo development, va a usar esos valores que definiste en el perfil development

2024-09-02 02:35 UTC, Fedesan14 commented on src/main/java/com/_up/megastore/services/implementations/MailSenderService.java
> +  }
Esto en realidad debería estar del lado del UserService ya que el EmailService solo debería tener la responsabilidad de mandar un mail con un contenido pero este no conoce el contenido sino que se lo pasan. Esto para evitar que si el día de mañana hay que agregar cada vez más correos para enviar al usuario no tendriamos 5 o 10 metodos diferentes uno para cada contenido en el servicio de email, sino que sólo la lógica de cómo se env´´ia mediante el uso del JavaMailSender

2024-09-02 02:35 UTC, Fedesan14 commented on src/main/java/com/_up/megastore/services/implementations/MailSenderService.java
> +    }
Acá estamos re-lanzando una excepción si no se puede enviar un mail y cambiandole el tipo de excepción, esto está mal, deberíamos seguir utilizando la excepción que ya te devuelve el javaMailSender, no nos sirve nada cambiar el tipo de excepción.

De hecho, utilizar la excepción que nos define la libreria, nos permite hacer cosas como por ejemplo:

1. Si no se puede enviar el mail, no pasa nada, seguimos adelante con la creación del usuario

Cosa que no podriamos hacer si catcheamos un RuntimeException porque no sabríamos a qué se debe esa excepción.

2024-09-02 02:35 UTC, Fedesan14 commented on src/main/java/com/_up/megastore/services/implementations/UserService.java
> +    mailSenderService.sendWelcomeEmail(user);
Siguiendo el comentario anterior, acá no estamos catcheando una posible excepcion que lance el service, lo que podria dar un error y hacer que el usuario no registre realmente solo porque no se mandó el mail.

Queremos evitar que el usuario se registre si nosotros tenemos un problema a la hora de enviar el mail? A mi en lo personal registraría de todas formas y si no se envió el mail bueno, cositas que pasan.

Eso lo podemos hacer haciendo esto

```suggestion
    String passwordEncoded = passwordEncoder.encode(createUserRequest.password());
    user.setPassword(passwordEncoded);
    try {
      mailSenderService.sendWelcomeEmail(user);
    } catch (MessagingException exception) {
      // Se loggea que no se pudo enviar el mail y sigue la ejecución del método
    }
```

2024-09-02 02:35 UTC, Fedesan14 commented on src/main/java/com/_up/megastore/data/model/User.java
> +    }
Pregunta, para que serviría esto? 🤔

2024-09-02 03:24 UTC, EzeSosa requested changes

2024-09-02 03:24 UTC, EzeSosa commented on src/main/java/com/_up/megastore/data/model/User.java
> +    }
Esto podría sacarse de acá ya que la responsabilidad de la clase User debería ser únicamente manejar los datos del usuario. Podrías crear una nueva clase `utils/PhoneNumberConversion.java` (o utilizar el directorio `pipes` que ya creaste) para no tener que modificar esta entity si el día de mañana cambia la lógica de conversión

2024-09-02 03:24 UTC, EzeSosa commented on src/main/java/com/_up/megastore/data/pipes/PhoneNumberConstraint.java
> +}
Masterclass total acá

2024-09-02 03:24 UTC, EzeSosa commented on src/main/java/com/_up/megastore/services/implementations/UserService.java
> +  private void checkIfEmailExistsOrThrowException(String email) {
La lógica está perfecta pero cambiaría el nombre

```suggestion
  private void ifEmailAlreadyExistsThrowException(String email) {
```
Como está redactado da a entender que si el email no existe tirás la excepción cuando debería ser lo contrario

2024-09-02 03:24 UTC, EzeSosa commented on src/main/java/com/_up/megastore/services/implementations/UserService.java
> +  private void checkIfUsernameExistsOrThrowException(String username) {
Lo mismo que la anterior
```suggestion
  private void ifUsernameAlreadyExistsThrowException(String username) {
```

2024-09-02 19:09 UTC, delgadomatias commented on src/main/java/com/_up/megastore/controllers/requests/CreateUserRequest.java
> +    String email,
Tenes razón, el @Email no valida un string vacío.

2024-09-02 19:19 UTC, delgadomatias commented on src/main/java/com/_up/megastore/services/implementations/MailSenderService.java
> +    }
Entonces como podría hacer? Podría hacer un catch de la excepción como esta e ignorarla?

2024-09-02 19:33 UTC, delgadomatias commented on src/main/java/com/_up/megastore/data/model/User.java
> +    }
En la base de datos se guarda el numero de teléfono estandarizado. Pero este proceso con el Constraint ocurre luego de guardarse, entonces, para el UserMapper, el telefono no esta formateado, entonces no coincide con el formato de la base de datos. 
Agregue ese método para que el Mapper lo utilice en la creación de las entidades de Usuario y mostrar el mismo numero que en la base de datos.

2024-09-02 19:37 UTC, delgadomatias commented on src/main/java/com/_up/megastore/services/implementations/UserService.java
> +  private void checkIfEmailExistsOrThrowException(String email) {
Tenes toda la razon, skill issue

2024-09-03 01:27 UTC, Fedesan14 commented on src/main/java/com/_up/megastore/services/implementations/MailSenderService.java
> +    }
@delgadomatias juntemonos para definir bien el alcance de esta historia de usuario con las nuevas actualizaciones sobre el mail. Podemos dividir esta historia en dos entre la creacion de un usuario y la activación de su cuenta

2024-09-03 14:46 UTC, closed without merging