Feat/update category
7-Seven-Up/megastore-backend pull request #26
Opened 2024-09-02 17:11 UTC by martinjcrosetto

New feature for update details of a product, allowing users to modify: name, description and superCategory.
Changes Made:

- UpdateCategoryRequest
- ICategoryController
- CategoryController
- ICategoryService
- CategoryService

2024-09-02 18:01 UTC, EzeSosa requested changes
Le estás agarrando la mano, felicitaciones! Habría que debatir en grupo lo de los nulos porque es importante para todos los update

2024-09-03 01:15 UTC, Fedesan14 approved these changes

2024-09-03 01:16 UTC, Fedesan14 commented
Buen laburo en este MR Crous

2024-09-03 04:03 UTC, EzeSosa approved these changes
Buena PR. Algunas cuestiones extra para la próxima:

- Evitar los imports generales (*) como ya hablamos
- Evitar declarar variables en memoria si no se les va a realizar alguna modificación (por ejemplo el superCategoryId en el updateCategory). Generalmente IntelliJ a estas cosas las pone como advertencia y tira una sugerencia de _inline variable_

Fijate que tenés conflictos con el merge en la clase ICategoryService. Tendrías que resolverlos para que Fede pueda mergear

2024-09-05 20:19 UTC, merged