feat: delete product
7-Seven-Up/megastore-backend pull request #30
Opened 2024-09-03 20:28 UTC by NicoAntu

Agregada la lógica y función para el borrado lógico de un producto del catalogo

2024-09-03 22:49 UTC, EzeSosa requested changes
Está bastante bien Nico, felicitaciones. Tendrías que corregir esas cosas que te marqué y enviarlo de nuevo

Otra cosa, tenés conflictos con el merge porque tu rama main seguramente esté desactualizada. Tendrías que resolver estos conflictos para que Fede pueda mergear. Si tenés problemas para hacerlo después lo vemos

2024-09-03 22:49 UTC, EzeSosa commented on src/main/java/com/_up/megastore/services/implementations/ProductService.java
> +        productRepository.save(product);
No está mal, pero agregaría un método más para validar que los productos que se deseen eliminar no estén ya eliminados. Esto permitiría hacer el código más legible y evitar procesamiento innecesario

```suggestion
        ifProductIsNotDeletedThrowException(productId);
        Product product = findProductByIdOrThrowException(productId);
        product.setDeleted(true);
        productRepository.save(product);
```

A esto lo podés hacer con Query Methods: https://www.baeldung.com/spring-data-derived-queries

2024-09-04 17:32 UTC, Fedesan14 reviewed
Quitando los comentarios del Eze yo lo veo bastante bien. Cuando corrijas lo que te dijo Eze lo reviso de nuevo y si esta todo okay lo aprobamos y mergeamos. Buen laburito

2024-09-04 23:51 UTC, EzeSosa requested changes
Bien Nico, corregís estas últimas cuestiones y ya está. Si hay un merge antes de que subas los cambios acordate de actualizarlo

2024-09-04 23:51 UTC, EzeSosa commented on src/main/java/com/_up/megastore/services/implementations/ProductService.java
> +    public void deleteProduct(UUID productId){
Banco este cambio

2024-09-04 23:51 UTC, EzeSosa commented on src/main/java/com/_up/megastore/services/implementations/ProductService.java
> +    public void ifProductIsNotDeletedThrowException(UUID productId){
No hace falta que esto sea public ya que sólo va a ser utilizado dentro de esta misma clase. Además el nombre está mal, estás diciendo que si el producto no está eliminado tirás la excepción cuando es lo contrario
```suggestion
    private void ifProductIsAlreadyDeletedThrowException(UUID productId) {
```

2024-09-04 23:51 UTC, EzeSosa commented on src/main/java/com/_up/megastore/services/implementations/ProductService.java
> +            throw new IllegalStateException("Product with id " + productId + " is already deleted.");
No está mal pero hay una forma más óptima de hacerlo: con Query Methods. Podrías probar implementando la lógica de lo siguiente
```suggestion
        if (productRepository.existsByProductIdAndDeletedTrue(productId)) {
            throw new IllegalStateException("Product with id " + productId + " is already deleted");
```
Dentro del IProductRepository

2024-09-04 23:51 UTC, EzeSosa commented on src/main/java/com/_up/megastore/services/interfaces/IProductService.java
> +    void ifProductIsNotDeletedThrowException(UUID productId);
Esto no hace falta que esté en la interfaz, sólo va a usarse dentro de la implementación

2024-09-05 00:55 UTC, delgadomatias requested changes

2024-09-05 00:55 UTC, delgadomatias commented on src/main/java/com/_up/megastore/controllers/interfaces/IProductController.java
No debería ir un PatchMapping (esto es para actualizar un producto). En este caso debería ser un DeleteMapping.
Ademas, esta duplicado, por lo cual esto ni siquiera compila.
Esta [documentación](https://developer.mozilla.org/es/docs/Web/HTTP/Methods) esta buena y te explica los distintos métodos HTTP.

2024-09-05 19:20 UTC, Fedesan14 requested changes

2024-09-05 19:20 UTC, Fedesan14 commented on src/main/java/com/_up/megastore/controllers/interfaces/IProductController.java
Se me pasó 👀 bien visto Mati, es cierto. Esto no debería ser un PATCH sino un DELETE ya que es el método Http que representa a una eliminaciòn

2024-09-05 19:20 UTC, Fedesan14 commented on src/main/java/com/_up/megastore/controllers/interfaces/IProductController.java
> +
Siguiendo con el comentario anterior, esto debería ser así

```suggestion
    @DeleteMapping(value = "/{productId}" )
    @ResponseStatus(HttpStatus.OK)
    ProductResponse deleteProduct(
            @PathVariable UUID productId
    );

```

2024-09-06 18:57 UTC, EzeSosa requested changes
Falta poco Nico, venís bien, probá corrigiendo estas cosas que te marqué y ya estaría. Una cosa más, en ProductController estás haciendo dos veces el import java.util.UUID; No me dejó corregirlo ahí pero te aviso por acá para que lo elimines, en IntelliJ los imports innecesarios te aparecen en color gris

2024-09-06 18:57 UTC, EzeSosa commented on src/main/java/com/_up/megastore/controllers/interfaces/IProductController.java
> +    );
Creo que acá no es correcto devolver el producto puesto que lo estamos 'eliminando'. Dejaría la función como void y en vez de devolver un OK devolvería un NO_CONTENT que significa que la petición se realizó con éxito pero que no hay nada que mostrar
```suggestion
    @ResponseStatus(HttpStatus.NO_CONTENT)
    void deleteProduct(
            @PathVariable UUID productId
    );
```

2024-09-06 18:57 UTC, EzeSosa commented on src/main/java/com/_up/megastore/services/implementations/ProductService.java
> +        return ProductMapper.toProductResponse(productRepository.save(product));
Si ponés el delete como void no haría falta devolver el product response por lo que esto debería quedarte así
```suggestion
        productRepository.save(product);
```

2024-09-06 18:57 UTC, EzeSosa commented on src/main/java/com/_up/megastore/services/interfaces/IProductService.java
> +    ProductResponse deleteProduct(UUID productId);
Con las correcciones anteriores esto quedaría así
```suggestion
    void deleteProduct(UUID productId);
```

2024-09-06 18:57 UTC, EzeSosa commented on src/main/java/com/_up/megastore/services/implementations/ProductService.java
>              throw new IllegalStateException("Product with id " + productId + " is already deleted.");
Esto me hace ruido porque dentro del cuerpo del deleteProduct ya estamos usando el findProductByIdOrThrowException. Creo que podría optimizarse si acá pasamos directamente el producto en vez de pegarle a la base de datos de nuevo. Esto podría quedar así

```suggestion
    private void ifProductIsNotDeletedThrowException(Product product) {
        if (product.isDeleted()){
            throw new ResponseStatusException("Product with id " + productId + " is already deleted.");
```

2024-09-06 18:57 UTC, EzeSosa commented on src/main/java/com/_up/megastore/services/implementations/ProductService.java
>          Product product = findProductByIdOrThrowException(productId);
Con lo que te marqué abajo esto podría quedar

```suggestion
        Product product = findProductByIdOrThrowException(productId);
        ifProductIsNotDeletedThrowException(product);
```

Y no somos redundantes

2024-09-06 19:26 UTC, Fedesan14 commented on src/main/java/com/_up/megastore/controllers/interfaces/IProductController.java
> +    );
No estoy de acuerdo con esto, por si bien es cierto que lo eliminamos, es un borrado lógico. El front podría utilizar esta actualización para marcar el producto de alguna forma al administrador o algo por el estilo, no es lo mismo que un borrado lógico en el que deja de existir, por lo que no tendría sentido devolverlo.

Esto lo dejo a criterio del equipo cómo quieren manejarlo

2024-09-06 20:38 UTC, EzeSosa commented on src/main/java/com/_up/megastore/controllers/interfaces/IProductController.java
> +    );
Me parece que desde el front no es necesaria esta respuesta (hay mecanismos que podemos usar para obtener nuevamente los productos y con mejores prácticas) pero me gustaría ver la opinión de @delgadomatias

2024-09-06 20:41 UTC, Fedesan14 commented on src/main/java/com/_up/megastore/controllers/interfaces/IProductController.java
> +    );
Para qué obtendrías de nuevo los productos si ya te lo puede devolver la misma petición de la eliminación ya actualizado? Estas haciendo otra petición más que solo le agrega delay

2024-09-06 21:01 UTC, delgadomatias commented on src/main/java/com/_up/megastore/controllers/interfaces/IProductController.java
> +    );
Imagino una acción desde el Frontend que te elimine el producto, para ello, ejecutaremos una función reductora que nos actualice el estado de dicho producto. Por lo tanto, la actualizacion en el lado del servidor se haría a través de la petición HTTP y la actualización del estado del lado del cliente justamente con el manejo del estado global.

Por lo tanto, una vez que eliminemos el producto el frontend ya sabe que producto se elimino y si se elimino de manera correcta. No necesita mas información.

2024-09-06 22:21 UTC, EzeSosa commented on src/main/java/com/_up/megastore/controllers/interfaces/IProductController.java
> +    );
Banco

2024-09-06 23:11 UTC, Fedesan14 commented on src/main/java/com/_up/megastore/controllers/interfaces/IProductController.java
> +    );
Es cierto que en este caso es una boludés, pero no es correcto que el frontend tenga lógica para actualizar los datos en su estado. Qué pasaría si eliminar (o cualquier otra cosa) incluyera cambiar más cosas en esa entidad, tendrías que tener lógica en el front de aquellas cosas que se tienen que cambiar, en vez de aprovechar la respuesta del backend que ya hizo los cambios correspondientes.

El estado de debería actualizarse acorde a los datos que devuelve el backend y no tener lógica para manejar el estado. Pero si quieren dejarlo así y manejar el estado de la app sabiendo ya cuál es la entidad que se borra, es otra opción que va a servir

2024-09-07 21:40 UTC, Fedesan14 approved these changes

2024-09-07 21:41 UTC, Fedesan14 commented
Buen laburo Nico, lo único, para los proximos MR hay que ir cerrando los comentarios a medida que se van resolviendo los comentarios que te dejamos, fijate que en cada comentario hay un "Resolve conversation". Si aplicas el cambio realizado que se te solicitó, le das a ese botón, para que despues al hacerte review no sea más quilombo

2024-09-08 20:25 UTC, delgadomatias approved these changes

2024-09-08 20:47 UTC, EzeSosa approved these changes

2024-09-08 21:04 UTC, merged