feat: register users
7-Seven-Up/megastore-backend pull request #33
Opened 2024-09-04 01:57 UTC by delgadomatias

Originalmente, teníamos una sola historia de usuario para registrar al usuario y enviarle un correo de bienvenida con el enlace para validar su cuenta. Decidí dividir esta historia en dos, cada una con sus respectivas funcionalidades.

Se implementó el registro de usuarios, codificando sus contraseñas (por ello, se instaló Spring Security como dependencia) y además se realizó una configuración predeterminada del mismo.

2024-09-04 01:59 UTC, delgadomatias commented on src/main/java/com/_up/megastore/controllers/requests/CreateUserRequest.java
Acá, anteriormente había definido el @Email de Jakarta, la verdad es que es bastante malo. Decidí implementar una expresión regular mucho mas fuerte.

2024-09-04 02:55 UTC, EzeSosa requested changes
Tremenda PR Mati, hermoso lo de las constraints. Habría que discutir después entre todos la posibilidad del AuthController para ahorrar trabajo a futuro

2024-09-04 02:55 UTC, EzeSosa commented on src/main/java/com/_up/megastore/controllers/requests/CreateUserRequest.java
> +    @Pattern(regexp = "^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}", message = "User email must be a valid email")
Buenísimo esto para tener en cuenta los @frvm.utn.edu.ar

2024-09-04 02:55 UTC, EzeSosa commented on src/main/java/com/_up/megastore/services/mappers/UserMapper.java
> +  }
Teniendo en cuenta que después tenemos que hacer tests, creo que no estaría mal separar la conversión del número de teléfono del mapper y dejarla en un método aparte privado dentro del servicio

```suggestion
  public static User toUser(CreateUserRequest createUserRequest, String convertedPhoneNumber) {
    return User.builder()
        .email(createUserRequest.email())
        .fullName(createUserRequest.fullName())
        .password(createUserRequest.password())
        .phoneNumber(convertedPhoneNumber)
        .username(createUserRequest.username())
        .build();
  }
```
De esta forma podemos testear la función del mapper y la conversión del número de teléfono de forma individual y separada

2024-09-04 02:55 UTC, EzeSosa commented on src/main/java/com/_up/megastore/services/implementations/UserService.java
> +  }
Me encantó esto

2024-09-04 02:55 UTC, EzeSosa commented on src/main/java/com/_up/megastore/controllers/interfaces/IUserController.java
> +@RequestMapping("/api/v1/users")
Este endpoint me hace ruido pensando a futuro en la autenticación. Generalmente se utiliza un AuthController donde se tienen los endpoints /auth/register y /auth/login y al UserController se lo deja para obtener información relacionada a los usuarios como su perfil o los pedidos que realizó.

Personalmente para esta funcionalidad (como es el registrar o signup) utilizaría un AuthController pero habría que discutirlo @delgadomatias @Fedesan14 @ValeLattanzi @martinjcrosetto @NicoAntu. Lo digo sobretodo pensando a futuro para que el register y el login no estén en controladores distintos

2024-09-04 02:55 UTC, EzeSosa commented on src/main/java/com/_up/megastore/data/pipes/PhoneNumberValidator.java
> +    }
A esto no lo entendí. Si el número es nulo no deberías devolver un false?

2024-09-04 02:55 UTC, EzeSosa commented on src/main/java/com/_up/megastore/services/implementations/UserService.java
> +  private void validateRequest(CreateUserRequest createUserRequest) {
Muy quisquilloso pero usaría un nombre más específico si después vamos a poder actualizar usuarios
```suggestion
  private void validateCreateUserRequest(CreateUserRequest createUserRequest) {
```

2024-09-04 03:06 UTC, delgadomatias commented
> Tremenda PR Mati, hermoso lo de las constraints. Habría que discutir después entre todos la posibilidad del AuthController para ahorrar trabajo a futuro

Estoy de acuerdo con vos, deberia ser el AuthController el encargado de registrar el usuario.

2024-09-04 17:23 UTC, Fedesan14 commented on src/main/java/com/_up/megastore/data/pipes/PhoneNumberValidator.java
> +    }
Supongo que retrona true porque si no existe el numero de teléfono es un dato válido, es obligatorio el numero de telefono es un dato opcional?

2024-09-04 17:24 UTC, Fedesan14 commented on src/main/java/com/_up/megastore/data/utilities/PhoneNumberConversion.java
> +    }
Mantendría la misma excepción, no la cambiaría a un RuntimeException

2024-09-04 17:28 UTC, Fedesan14 commented on src/main/java/com/_up/megastore/controllers/interfaces/IUserController.java
> +@RequestMapping("/api/v1/users")
Sip, es cierto que generalmente para lo que tenga que ver con signin o login se utiliza el endpoint /auth, que después deriva en tener un AuthController y un AuthService, pero tambien es diseño de cómo lo desea el equipo. En particular prefiero tener el /auth para lo que es autentication y autorización y /users para la eliminacion/actualizacion de los datos de un usuario

2024-09-04 17:30 UTC, Fedesan14 requested changes
Te dejo el comentario sobre mantener la misma excepción, el resto lo veo bastante bien, good work

2024-09-04 18:02 UTC, EzeSosa commented on src/main/java/com/_up/megastore/data/pipes/PhoneNumberValidator.java
> +    }
Es obligatorio en la request, lo estuve probando, pero de todos modos creo que no habría forma de que llegue hasta ese punto siendo nulo. Es un vacío legal(?

2024-09-04 18:08 UTC, Fedesan14 commented on src/main/java/com/_up/megastore/data/pipes/PhoneNumberValidator.java
> +    }
Entonces quitemoslo porque solo va a ser código que genere dudas el día de mañana de por qué está

2024-09-04 18:09 UTC, delgadomatias commented on src/main/java/com/_up/megastore/data/utilities/PhoneNumberConversion.java
> +    }
Entonces debería ignorar el error que obtengo de la excepción? 
Generalmente en estos casos, se loggea para saber internamente que fue lo que paso, o no?

2024-09-04 18:10 UTC, delgadomatias commented on src/main/java/com/_up/megastore/data/pipes/PhoneNumberValidator.java
> +    }
La idea de dejar eso en true es que existen otros Constraint justamente para validar eso. Si usas este en conjunto con el @NotBlank, al retornar true acá, el que manejaría ese error seria el @NotBlank.

2024-09-04 18:21 UTC, Fedesan14 commented on src/main/java/com/_up/megastore/data/utilities/PhoneNumberConversion.java
> +    }
Al catchear la excepción lo que vos estas haciendo es que no lance un error al cliente retornando un error 500 y harás lo que vos necesités, supongamos que deseas loggear, en ese caso tendrias que hacer

```suggestion
    } catch (NumberParseException e) {
      logger.info("There was an error parsing the phone number")
    }
```

pero lo que estas haciendo en este codigo es catchear la excepcion del tipo NumberParseException para lanzar otra del tipo RuntimeException, para eso deja la misma que ya se lanzó previamente y podes en un ExceptionHandler manejar la exception de NumberParseException como vos quieras

2024-09-04 18:47 UTC, delgadomatias commented on src/main/java/com/_up/megastore/data/utilities/PhoneNumberConversion.java
> +    }
Es que yo dejaría que tire error en el cliente indicando que no se pudo parsear el numero. Aunque en este caso nunca pasaría porque lo estoy validando con una constraint.
Me podes tirar algún centro? El método parse ya me obliga a manejar la excepción (en la firma dice que tira la misma)

2024-09-04 20:10 UTC, EzeSosa commented on src/main/java/com/_up/megastore/data/utilities/PhoneNumberConversion.java
> +    }
¿Y una excepción personalizada? Creo que el problema de dejar la NumberParseException es que es [chequeada](https://openwebinars.net/blog/introduccion-a-poo-en-java-excepciones/#:~:text=de%20cada%20secci%C3%B3n.-,Tipos%20de%20excepciones%20en%20Java,en%20un%20bloque%20try%2Dcatch.) y ensucia todos los métodos desde el service hasta esta clase. Por otro lado, por más que en el cliente se valide la excepción que tiene que existir porque el back se podría probar con Postman o cualquier cliente distinto

2024-09-04 20:16 UTC, delgadomatias commented on src/main/java/com/_up/megastore/data/utilities/PhoneNumberConversion.java
> +    }
A ver, el flujo es el siguiente:
- Mandas el numero de teléfono por el body
- Si no es correcto, el constraint del PhoneNumber tira el error y el mensaje.
- Si es correcto, pasaría a guardarse a la base de datos y se convierte el numero con el Converter.

Es decir, solo se utiliza este método una vez que pase del constraint.

2024-09-04 20:34 UTC, EzeSosa commented on src/main/java/com/_up/megastore/data/utilities/PhoneNumberConversion.java
> +    }
Entiendo, si **no hay ninguna forma de que pase el constraint y aun así no se pudiese convertir** entonces podrías dejar esa excepción aunque desconozco cuál es la mejor práctica en estos casos

2024-09-04 20:48 UTC, Fedesan14 commented on src/main/java/com/_up/megastore/data/utilities/PhoneNumberConversion.java
> +    }
Create una custom exception como la siguiente clase, fijate que hay un package que es exceptions, podes crear un paquete dentro de ese que sea custom_exceptions
```
public class ParsePhoneNumberException extends RuntimeException {
    public ParsePhoneNumberException(String message, Throwable cause) {
        super(message, cause);
    }
}
```

y en el metodo harias lo siguiente

```suggestion
        } catch (NumberParseException e) {
            throw new ParsePhoneNumberException(e.getMessage(), e.getCause());
        }
```

2024-09-04 23:41 UTC, EzeSosa requested changes
Capaz me estoy equivocando pero me parece que se podría mover el registro del usuario al UserService dejando al Auth la responsabilidad de exponer el endpoint y redirigir la petición al UserService. Lo digo para poder reutilizar la validación del username y del email en la actualización del usuario (método que va a ir sí o sí dentro del UserController). Me gustaría ver tu opinión @Fedesan14

2024-09-04 23:41 UTC, EzeSosa commented on src/main/java/com/_up/megastore/data/model/User.java
> +  @Convert(converter = PhoneNumberConverter.class)
Buenísimo esto

2024-09-04 23:41 UTC, EzeSosa commented on src/main/java/com/_up/megastore/services/implementations/AuthService.java
> +  }
A esto lo movería a UserService pensando después en el actualizado de datos. Si definimos que un usuario puede actualizar su username y su email, esta misma validación podría reutilizarse. Para ello, debería estar en UserService

2024-09-04 23:41 UTC, EzeSosa commented on src/main/java/com/_up/megastore/services/implementations/AuthService.java
> +  }
Con esto lo mismo. Creo que es posible delegar la responsabilidad de crear un usuario al UserService para mantener todo del mismo lado

2024-09-04 23:41 UTC, EzeSosa commented on src/main/java/com/_up/megastore/services/interfaces/IUserService.java
> +  void ifUsernameAlreadyExistsThrowException(String username);
El problema de haberlo trabajado dividiendo las validaciones es este. Estos métodos no deberían exponerse a nivel interfaz ya que sólo deberían ser utilizados dentro del UserService (como private voids)

2024-09-05 00:04 UTC, Fedesan14 commented on src/main/java/com/_up/megastore/services/implementations/AuthService.java
> +  }
Más que para reutilizarse, es por responsabilidades. En Auth además de manejar la creación de un usuario, el día de mañana vas a tener que hacer la authentication y authorization, por eso se separa del UserController. Está bien que las validaciones se hagan desde el UserService porque es su responsabilidad y que el AuthService utilice ésto para luego hacer otras cosas como generar un JWT, validar un JWT y saber sus roles y permisos, etc

2024-09-05 00:10 UTC, Fedesan14 commented on src/main/java/com/_up/megastore/services/implementations/AuthService.java
> +  }
Siguiendo un poco lo que decía Eze, esto en realidad debería ser como una especie de pasamano, porque la responsabilidad de creación de un usuario la tiene el UserService

```suggestion
  public void signUp(SignUpRequest signUpRequest) {
    userService.signUp(signUpRequest);
  }
```

¿Por qué esto así? Porque en realidad el día de mañana cuando tengamos el login, en este service vamos a manejar la lógica para generar todo lo que tenga que ver con la autorización de un usuario

2024-09-05 00:15 UTC, delgadomatias commented on src/main/java/com/_up/megastore/data/utilities/PhoneNumberConversion.java
> +    }
No funciona. 
Para replicar esto, tuve que sacar el constraint del numero de teléfono, y me tira un error de transacción de JPA.

2024-09-05 00:19 UTC, Fedesan14 commented on src/main/java/com/_up/megastore/data/utilities/PhoneNumberConversion.java
> +    }
Mmmm, bueno... Me parece que no vale la pena perder el tiempo en esto por simplemente dejarlo más bonito, podemos dejarlo como deuda técnica y después vemos cómo lo modificamos

2024-09-05 00:27 UTC, EzeSosa approved these changes

2024-09-05 20:24 UTC, Fedesan14 approved these changes
Apruebo el MR y lo mergeo, lo unico @delgadomatias , parece que hubieras usado algo formateador de código y esto hace que en tu MR figure un motnon de cambios que no tienen nada que ver, por ejemplo el pom.xml, no puedo diferenciar las dependencias que agregaste de los cambios por el formateador de manera fácil. 

En estos casos es mejor hacer un MR aparte para formatear main y luego hacer tu MR para que luego github no pueda diferenciar los cambios por formateo y solo lo que es relevante

2024-09-05 20:25 UTC, merged