feat: restore-size
7-Seven-Up/megastore-backend pull request #39
Opened 2024-09-05 20:58 UTC by martinjcrosetto

Se agregó un endpoint para restaurar los productos previamente eliminados. Para esto se utilizó un PatchMapping, puesto que, solamente se actualiza el atributo "deleted" a false en la entidad.

2024-09-07 20:23 UTC, EzeSosa requested changes
Acordate siempre de probar la aplicación con Postman antes de hacer las PR! Buen trabajo de todos modos, sólo hay que corregir esas cositas

2024-09-07 20:23 UTC, EzeSosa commented on src/main/java/com/_up/megastore/controllers/interfaces/ISizeController.java
> +    @PostMapping (value = "{/sizeId}/restore") @ResponseStatus(HttpStatus.OK)
Esto está mal escrito. Si encerrás a la barra dentro de las llaves el endpoint queda inválido. Esto compila pero Spring no es capaz de mapear el endpoint por lo que la aplicación no corre
```suggestion
    @PostMapping (value = "/{sizeId}/restore") @ResponseStatus(HttpStatus.OK)
```

2024-09-07 20:23 UTC, EzeSosa commented on src/main/java/com/_up/megastore/services/implementations/SizeService.java
> +    }
Siguiendo la corrección que le hicimos al Nico (y que no aplicamos en el restaurar producto porque somos re inteligentes) esto podría optimizarse para no pegarle dos veces a la base de datos

```suggestion
    public void validateSizeForRestoration(Size size) {
        if (!size.isDeleted()) {
            throw new ResponseStatusException(HttpStatus.BAD_REQUEST, "Size with id " + sizeId + " is not deleted." );
        }
    }
```

2024-09-07 20:23 UTC, EzeSosa commented on src/main/java/com/_up/megastore/services/implementations/SizeService.java
> +        Size size = findSizeByIdOrThrowException(sizeId);
Siguiendo con el comentario anterior acá habría que invertir el orden

```suggestion
        Size size = findSizeByIdOrThrowException(sizeId);
        validateSizeForRestoration(size);
```

2024-09-08 23:58 UTC, EzeSosa requested changes
Casi está Crous. Muy buen laburo anyways

2024-09-08 23:58 UTC, EzeSosa commented on src/main/java/com/_up/megastore/services/implementations/SizeService.java
>          }
No hace falta pasar el sizeId si ya la podés obtener del size usando el getter
```suggestion
    public void validateSizeForRestoration(Size size){
        if(!size.isDeleted()){
            throw new ResponseStatusException(HttpStatus.BAD_REQUEST, "Size with id " + size.getSizeId() + " is not deleted." );
        }
```

2024-09-08 23:58 UTC, EzeSosa commented on src/main/java/com/_up/megastore/services/implementations/SizeService.java
> +        validateSizeForRestoration(size, sizeId);
Esto debería quedar así
```suggestion
        validateSizeForRestoration(size);
```

2024-09-09 01:32 UTC, Fedesan14 requested changes

2024-09-09 01:32 UTC, Fedesan14 commented on src/main/java/com/_up/megastore/services/implementations/SizeService.java
> +    }
El nombre del método debería ser más representativo a lo que hace, en este caso solo estamos viendo si está eliminado, por lo que podría llamarse de otra manera

```suggestion
    public void ifSizeIsAlreadyDeletedThrowException(Size size) {
        if(!size.isDeleted()){
            throw new ResponseStatusException(HttpStatus.BAD_REQUEST, "Size with id " + size.getSizeId() + " is not deleted." );
        }
    }
```

2024-09-09 02:16 UTC, EzeSosa approved these changes

2024-09-09 16:34 UTC, EzeSosa requested changes

2024-09-09 16:34 UTC, EzeSosa commented on src/main/java/com/_up/megastore/services/implementations/SizeService.java
> +    public void ifSizeIsAlreadyDeletedThrowException(Size size) {
El método está mal redactado, estás diciendo que si está eliminado tirás una excepción cuando debería ser lo contrario
```suggestion
    public void ifSizeIsNotDeletedThrowException(Size size) {
```

2024-09-09 23:05 UTC, Fedesan14 approved these changes

2024-09-09 23:05 UTC, Fedesan14 commented
@martinjcrosetto hay conflictos, resolvemos y lo mergeo

2024-09-10 01:00 UTC, Fedesan14 approved these changes

2024-09-10 01:01 UTC, merged