ref: restore-category
7-Seven-Up/megastore-backend pull request #40
Opened 2024-09-05 21:04 UTC by martinjcrosetto

Se agregó un endpoint para restaurar las categorias de productos previamente eliminadas. Para esto se utilizó un PatchMapping, puesto que, solamente se actualiza el atributo "deleted" a false en la entidad.

2024-09-05 22:58 UTC, EzeSosa requested changes
Fijate si podés corregir esto que te marqué así mantenemos un estándar en cómo hacemos las operaciones

2024-09-05 22:58 UTC, EzeSosa commented on src/main/java/com/_up/megastore/controllers/interfaces/ICategoryController.java
> +    CategoryResponse restoreCategory(@PathVariable UUID categoryId);
A esto lo hablamos con @Fedesan14 en la PR del restaurar producto #27. El método debería ser Post porque se utiliza para dar de alta el recurso al que antes no se podía acceder (esa categoría 'borrada').

2024-09-05 22:58 UTC, EzeSosa commented on src/main/java/com/_up/megastore/services/implementations/CategoryService.java
> +    }
Para dejar todos los restore iguales podríamos agregar la lógica para evitar restaurar productos que no están borrados. Esto se hizo en #27 
```suggestion
    public CategoryResponse restoreCategory(UUID categoryId){
        validateCategoryForRestoration(categoryId);
        Category category = findCategoryByIdOrThrowException(categoryId);
        category.setDeleted(false);
        return CategoryMapper.toCategoryResponse(categoryRepository.save(category));
    }
```

2024-09-06 13:33 UTC, EzeSosa approved these changes

2024-09-06 19:25 UTC, Fedesan14 requested changes

2024-09-06 19:25 UTC, Fedesan14 commented on src/main/java/com/_up/megastore/controllers/interfaces/ICategoryController.java
> +
Falta agregar la acción en el PATH que indica la razón de ser de este endpoint

```suggestion
    @PostMapping(value = "/{categoryId}/restore") @ResponseStatus(HttpStatus.OK)
    CategoryResponse restoreCategory(@PathVariable UUID categoryId);

```

2024-09-07 17:04 UTC, Fedesan14 approved these changes

2024-09-07 17:04 UTC, merged