feat: delete category
7-Seven-Up/megastore-backend pull request #42
Opened 2024-09-07 18:06 UTC by martinjcrosetto

Se agregó un endpoint para eliminar una categoría. Se utilizó un DeleteMapping puesto que se actualiza solamente el atributo "deleted" de una categoría.

2024-09-07 20:35 UTC, EzeSosa requested changes
Buen laburo! Quedan esas cosas para corregir y estamos. Ojo después con los conflictos a la hora de mergear

2024-09-07 20:35 UTC, EzeSosa commented on src/main/java/com/_up/megastore/controllers/interfaces/ICategoryController.java
> +    CategoryResponse deleteCategory(@PathVariable UUID categoryId);
Acá no deberíamos devolver nada si queremos mantener un estándar de todas las eliminaciones
```suggestion
    void deleteCategory(@PathVariable UUID categoryId);
```

2024-09-07 20:35 UTC, EzeSosa commented on src/main/java/com/_up/megastore/data/repositories/ICategoryRepository.java
> +    Optional<Category> findByCategoryIdAndDeletedIsFalse(UUID categoryId);
Los optionals están buenos para cuando queremos obtener una entidad que después vamos a reutilizar o actualizar. En este caso, como sólo querés hacer la validación podrías refactorizar este método para que te devuelva un booleano directamente
```suggestion
    boolean existsByCategoryIdAndDeletedIsFalse(UUID categoryId);
```
De todos modos creo que este método podría no utilizarse

2024-09-07 20:35 UTC, EzeSosa commented on src/main/java/com/_up/megastore/exception/ExceptionControllerAdvice.java
> +    }
Cuándo ocurriría esta excepción? Pregunto porque no la vi nunca

2024-09-07 20:35 UTC, EzeSosa commented on src/main/java/com/_up/megastore/services/implementations/CategoryService.java
> +    }
Esto podría eliminarse si optimizamos el método para obtener primero la categoría con el findByCategoryIdOrThrowException

2024-09-07 20:35 UTC, EzeSosa commented on src/main/java/com/_up/megastore/services/implementations/CategoryService.java
> +    }
Esto podría optimizarse para pegarle sólo una vez a la bd

```suggestion
    public CategoryResponse deleteCategory(UUID categoryId){
        Category category = findCategoryByIdOrThrowException(categoryId);
        ifCategorySubcategoriesExistsThrowException(category);
        category.setDeleted(true);
        categoryRepository.save(category);
    }
```

2024-09-07 21:37 UTC, Fedesan14 commented on src/main/java/com/_up/megastore/exception/ExceptionControllerAdvice.java
> +    }
Esta excepción es de Hibenarte si no me equivoco, y sucede cuando hay alguna reestriccion al ejecutar una query

2024-09-09 00:19 UTC, martinjcrosetto commented on src/main/java/com/_up/megastore/data/repositories/ICategoryRepository.java
> +    Optional<Category> findByCategoryIdAndDeletedIsFalse(UUID categoryId);
pero no debía utilizar un JPA query method?

2024-09-09 01:30 UTC, Fedesan14 requested changes

2024-09-09 01:30 UTC, Fedesan14 commented on src/main/java/com/_up/megastore/services/implementations/CategoryService.java
> +    public void getCategoryByIdAndDeletedFalseOrThrowException(Category category){
Por qué este método se llama "getCategory...()" si no retorna ninguna categoria? Los nombres de los métodos deben ser representativos a lo que hacen, esto sería más algo como

```suggestion
    public void validateIfCategoryIsDeletedAndThrowException(Category category){
```

2024-09-09 01:30 UTC, Fedesan14 commented on src/main/java/com/_up/megastore/controllers/interfaces/ICategoryController.java
> +    void deleteCategory(@PathVariable UUID categoryId);
Al no retornar nada, el tipo de status debería ser un 204 NO_CONTENT, el cual especifica que la petición terminó correctamente pero no se devuelve ningun tipo de información

```suggestion
    @DeleteMapping(value = "/{categoryId}") @ResponseStatus(HttpStatus.NO_CONTENT)
    void deleteCategory(@PathVariable UUID categoryId);
```

2024-09-09 01:30 UTC, Fedesan14 commented on src/main/java/com/_up/megastore/services/implementations/CategoryService.java
> +    }
Tengo entendido que si intentás eliminar algo que tiene una relación con otras entidades, ya te va a tirar la excepción, por qué lo chequeariamos y lanzamos la excepción si ya lo hace hibernate?

Sobre esto tenemos dos opciones

1. Usar cascada y eliminamos todas las categorias hijas al mismo timepo
2. Quitar la relación padre/hija a mano para que podamos eliminar la categoria que estamos intentando borrar
3. No hacer nada y dejar que lance la excepción

Lo dejo a criterio del equipo @EzeSosa @delgadomatias @ValeLattanzi

2024-09-09 02:15 UTC, EzeSosa commented on src/main/java/com/_up/megastore/services/implementations/CategoryService.java
> +    }
Creo que quedamos en que no iba a ser posible eliminar una categoría con subcategorías, teniendo en cuenta esto yo optaría por la opción 3 y manejamos la excepción en el controller advice

2024-09-09 20:28 UTC, EzeSosa approved these changes

2024-09-09 20:28 UTC, EzeSosa commented on src/main/java/com/_up/megastore/data/model/Category.java
> +    @OneToMany(mappedBy = "superCategory", cascade = {CascadeType.ALL})
Esto está bien y creo que habría que corregirlo en los productos. Con el mapeo por 'category Id' la lista de subcategorías tenía un elemento (la propia categoría) y no nos permitía hacer las validaciones. De todos modos me gustaría que verifiques esto @Fedesan14

2024-09-09 21:41 UTC, Fedesan14 commented on src/main/java/com/_up/megastore/data/model/Category.java
> +    @OneToMany(mappedBy = "superCategory", cascade = {CascadeType.ALL})
Mmm, me perdí, al mapear por categoryId si tenias una lista de 3 subcategorias, en la lista figuraban dos categorias hijas y la categoria en si misma haciendo un bucle?

Si vamos a este ejemplo

![image](https://github.com/user-attachments/assets/2fe99bd2-e52f-4cb3-a7a7-b54216066495)

supongamos "Computacion": el superCategory es "Tecnologia" y la lista de subCategorias son ["Componentes para PC", "Impresion", "Tablet y accesorios"]

Estaría mal que la lista de subcategories este mapeada por "superCategory" porque no hay ninguna relación entre esas entidades mas allá que la entidad que estamos analizando "Computación".

2024-09-09 22:13 UTC, EzeSosa commented on src/main/java/com/_up/megastore/data/model/Category.java
> +    @OneToMany(mappedBy = "superCategory", cascade = {CascadeType.ALL})
Sí, ocurría lo primero que decís. Sobre tu ejemplo, si Componentes de PC, Impresión y Tablets y accesorios tienen como superCategory a Computación y, a su vez, Computación tiene como superCategory a Tecnología decís que no se mapea?

Yo tengo entendido que el mappedBy='superCategory' le indica a hibernate que busque a los registros cuyo superCategory sea esa misma categoría. 

En este caso, mapeando con categoryId teníamos un bucle que fue eliminado con superCategory.

Habría que probar el ejemplo que vos planteás y de última agregamos una condición más para eliminar a las categorías que sólo se tengan como superCategory a sí mismas

2024-09-09 23:03 UTC, Fedesan14 commented on src/main/java/com/_up/megastore/data/model/Category.java
> +    @OneToMany(mappedBy = "superCategory", cascade = {CascadeType.ALL})
Se me ocurre cuál puede ser el problema, esto pasa cuando se hace un POST de una subcategoria?

2024-09-09 23:24 UTC, EzeSosa commented on src/main/java/com/_up/megastore/data/model/Category.java
> +    @OneToMany(mappedBy = "superCategory", cascade = {CascadeType.ALL})
Pasaba al momento de hacer un delete de una categoría supuestamente sin categorías... @martinjcrosetto  contanos bien qué ocurría

2024-09-09 23:28 UTC, martinjcrosetto commented on src/main/java/com/_up/megastore/data/model/Category.java
> +    @OneToMany(mappedBy = "superCategory", cascade = {CascadeType.ALL})
Al hacer un delete a una categoria utilizando postman, a la cual no se le habia asignado subcategorias, tiraba un error 409.

2024-09-09 23:57 UTC, Fedesan14 commented on src/main/java/com/_up/megastore/data/model/Category.java
> +    @OneToMany(mappedBy = "superCategory", cascade = {CascadeType.ALL})
Mmm, lo voy a debugear y ver qué pasa. Dejemos la PR abierta por ahora

2024-09-10 01:06 UTC, Fedesan14 commented on src/main/java/com/_up/megastore/data/model/Category.java
> +    @OneToMany(mappedBy = "superCategory", cascade = {CascadeType.ALL})
Cierro hilo, ya entendí por qué funca con el superCategory así que dejemoslo así

2024-09-10 01:08 UTC, Fedesan14 requested changes

2024-09-10 01:08 UTC, Fedesan14 commented on src/main/java/com/_up/megastore/data/repositories/ICategoryRepository.java
> +import java.util.Optional;
Creo que este import no se usa

2024-09-10 02:55 UTC, merged