Feat: delete size
7-Seven-Up/megastore-backend pull request #43
Opened 2024-09-07 18:07 UTC by martinjcrosetto

Se agregó un endpoint para eliminar un tamaño de producto. Se utilizó un DeleteMapping puesto que se actualiza solamente el atributo "deleted" de un tamaño de producto.

2024-09-07 18:30 UTC, Fedesan14 requested changes
Te dejo estos comentarios, pero te podes ahorras una query a la DB obteniendo primero el Size y luego verificando el valor de su valor "deleted" sin usar el existsById

2024-09-07 18:30 UTC, Fedesan14 commented on src/main/java/com/_up/megastore/services/implementations/SizeService.java
> +    }
El nombre de este método está mal ya que se lanza la exception si NO existe

```suggestion
    public void ifSizeDoesNotExistsThrowException(UUID sizeId){
        if(!sizeRepository.existsById(sizeId)){
            throw new NoSuchElementException("Size with id " + sizeId + " does not exist.");
        }
    }
```

2024-09-07 18:30 UTC, Fedesan14 commented on src/main/java/com/_up/megastore/services/implementations/SizeService.java
> +    }
Lo mismo con este metodo, ya que no solo estas verificando si el size no está eliminado, sino que ademas estás retornando el size, seria más algo como esto

```suggestion
    public Size getSizeByIdAndDeletedFalseOrThrowException(UUID sizeId){
        return sizeRepository.findBySizeIdAndDeletedIsFalse(sizeId)
                .orElseThrow(() -> new NoSuchElementException("Size with id " + sizeId + " is deleted."));
    }
```

2024-09-09 01:34 UTC, Fedesan14 requested changes

2024-09-09 01:34 UTC, Fedesan14 commented on src/main/java/com/_up/megastore/controllers/interfaces/ISizeController.java
> +    void deleteSize(@PathVariable UUID sizeId);
Esto como lo expliqué en otro review esto debería devolver un NO_CONTENT ya que no retornamos ningun payload

```suggestion
    @DeleteMapping (value = "/{sizeId}") @ResponseStatus(HttpStatus.NO_CONTENT)
    void deleteSize(@PathVariable UUID sizeId);
```

2024-09-09 01:34 UTC, Fedesan14 commented on src/main/java/com/_up/megastore/services/implementations/SizeService.java
> +    public void ifSizeIsNotDeletedThrowException(Size size){
El nombre del método está mal porque se lanza la excepción SI ESTÁ eliminado

```suggestion
    public void ifSizeIsDeletedThrowException(Size size){
```

2024-09-09 02:18 UTC, EzeSosa requested changes
Dejo un comentario más para sumar a las correcciones de Fede. Buen laburo

2024-09-09 02:18 UTC, EzeSosa commented on src/main/java/com/_up/megastore/data/repositories/ISizeRepository.java
> +    Optional<Size> findBySizeIdAndDeletedIsFalse(UUID sizeId);
Este método no se utiliza en ningún momento, podría eliminarse

2024-09-09 23:04 UTC, Fedesan14 approved these changes

2024-09-09 23:04 UTC, merged