feat: read-category
7-Seven-Up/megastore-backend pull request #47
Opened 2024-09-10 03:05 UTC by martinjcrosetto

Se agregaron los end points para consultar las categorías por id

2024-09-10 13:31 UTC, EzeSosa requested changes
Acordate siempre de probar todo con Postman antes de hacer las PR

2024-09-10 20:21 UTC, Fedesan14 reviewed
Quitando el comentario que te dejo Eze, agrega tambien para obtener todas las categorias

2024-09-11 05:24 UTC, EzeSosa requested changes
Más allá del detalle de la contraseña (la voy a probar con tu correo después) lo veo bastante bien. La paginación es un gran recurso para obtener información. Buen laburo!

2024-09-11 05:24 UTC, EzeSosa commented on src/main/resources/application.yaml
> +    password: ${DB_PASSWORD:martin1234}
Tratemos de no cambiar las propiedades del application.yaml en lo posible. Incluso, para conectarte a tu propia base de datos no hace falta que estés cambiando y recambiando la contraseña, podrías utilizar una variable de entorno

2024-09-11 22:12 UTC, Fedesan14 approved these changes

2024-09-11 22:12 UTC, merged