Feat/recover password
7-Seven-Up/megastore-backend pull request #55
Opened 2024-09-14 23:02 UTC by ValeLattanzi

# Changes: 
* Added an endpoint to send email to recover user's password
* Added an endpoint to update user's password

2024-09-14 23:32 UTC, Fedesan14 requested changes

2024-09-14 23:32 UTC, Fedesan14 commented on src/main/java/com/_up/megastore/controllers/interfaces/IUserController.java
> +  void recoverPassword(@PathVariable UUID userId, @RequestParam String newPassword, @RequestParam UUID recoverPasswordToken);
Los parametros de las contraseñas deberian ir por body no como request param, deberias crear un DTO "RecoverPasswordRequest" que contenga ambos parametros como atributos

```suggestion
  void recoverPassword(@PathVariable UUID userId, @RequestBody RecoverPasswordRequest recoverdPasswordRequest);
```

Además deberias agregar la repetición de la nueva contraseña

2024-09-14 23:32 UTC, Fedesan14 commented on src/main/java/com/_up/megastore/controllers/interfaces/IUserController.java
> +  void recoverPassword(@PathVariable UUID userId, @RequestParam String newPassword, @RequestParam UUID recoverPasswordToken);
Estos al no devolver nada, deberian tener un response status 204 NO_CONTENT

```suggestion
  @PostMapping("/recover-password/send-email")
  @ResponseStatus(HttpStatus.NO_CONTENT)
  void sendEmailToRecoverPassword(@RequestParam String email);

  @PostMapping("/{userId}/recover-password")
  @ResponseStatus(HttpStatus.NO_CONTENT)
  void recoverPassword(@PathVariable UUID userId, @RequestParam String newPassword, @RequestParam UUID recoverPasswordToken);
```

2024-09-14 23:32 UTC, Fedesan14 commented on src/main/java/com/_up/megastore/services/implementations/UserService.java
> +            .orElseThrow(() -> new RuntimeException("Token is invalid or user not exists."));
Acá deberíamos usar otro tipo de exception, un RuntimeException es MUY genérico, Spring tiene un tipo de exception que nos permite, además, asignarle un HTTP status al error

```suggestion
            .orElseThrow(() -> new ResponseStatusException(HttpStatus.BAD_REQUEST, "Token is invalid or user not exists."));
```

2024-09-14 23:32 UTC, Fedesan14 commented on src/main/java/com/_up/megastore/services/implementations/UserService.java
> +    user.setPassword(passwordEncoder.encode(newPassword));
Antes de cambiar su contraseña, deberiamos validar que el usuario haya ingresado la contraseña como el realmente quería, para eso tendriamos que hacer que el usuario escriba dos veces la contraseña y desde el servidor validar que ambos valores sean iguales

2024-09-14 23:32 UTC, Fedesan14 commented on src/main/java/com/_up/megastore/services/implementations/UserService.java
> +              "&token=" + user.getRecoverPasswordToken();
No enviemos el ID del usuario por una URL, este dato nunca se deberia mostrar

2024-09-14 23:32 UTC, Fedesan14 commented on src/main/java/com/_up/megastore/services/implementations/UserService.java
> +    User user = findUserByEmailOrThrowException(email);
Acá no hace falta que verifiquemos previamente si existe el usuario porque posteriormente lo obtenemos -y si no existe lanzamos una exception-

```suggestion
    User user = findUserByEmailOrThrowException(email);
```

2024-09-14 23:32 UTC, Fedesan14 commented on src/main/java/com/_up/megastore/data/model/User.java
> +  private final UUID recoverPasswordToken = UUID.randomUUID();
Estamos generando el token cuando se registra el usuario, pero este dato debería generarse y setearse cuando se envia el token. Osea, deberiamos generar el token cada vez que el usuario quiera recuperar su contraseña y no usar siempre el mismo porque si alguien intercepta el token, alguien podria cambiarle la contraseña al usuario cada vez que el cliente lo cambia

2024-09-14 23:40 UTC, EzeSosa requested changes
Te dejo esas correcciones que son más que nada detalles, pero me gustó mucho el laburo.

Unas cositas más:

1. Habría que hacer el envío de los correos asíncronos porque demoran mucho el procesamiento de las request. Podríamos hacerlo en esta PR si todos estamos de acuerdo @Fedesan14 @delgadomatias @martinjcrosetto @NicoAntu 
2. Si tenés un poco más de tiempo para la próxima estaría genial que expliques un poco el flujo de las requests para la recuperación, una descripción cortita

Good work

2024-09-14 23:40 UTC, EzeSosa commented on src/main/java/com/_up/megastore/controllers/interfaces/IUserController.java
> +  void recoverPassword(@PathVariable UUID userId, @RequestParam String newPassword, @RequestParam UUID recoverPasswordToken);
Acá podríamos usar un body en vez de recibir como parámetros la password y el token
 ```suggestion
  @PostMapping("/{userId}/recover-password")
  void recoverPassword(@PathVariable UUID userId, @RequestBody RecoverPasswordRequest recoverPasswordRequest);
```

2024-09-14 23:40 UTC, EzeSosa commented on src/main/java/com/_up/megastore/services/implementations/UserService.java
> +      throw new RuntimeException("User not found");
Esto es innecesario porque después estás haciendo un findByEmailOrThrowException (que tira la excepción si el mail no existe). Podría borrarse así evitamos una query a la db

2024-09-14 23:40 UTC, EzeSosa commented on src/main/java/com/_up/megastore/services/implementations/UserService.java
> +    return userRepository.findByEmailAndDeletedIsFalse(email).orElseThrow(() -> new RuntimeException("User not found"));
En vez de tirar una RuntimeException (que en nuestro ControllerAdvice la relacionamos con fallas en la subida de imágenes) podrías tirar una ResponseStatusException
```suggestion
    return userRepository.findByEmailAndDeletedIsFalse(email)
         .orElseThrow(() -> new ResponseStatusException("User with email "+email+" does not exist."));
```

2024-09-14 23:40 UTC, EzeSosa commented on src/main/java/com/_up/megastore/services/implementations/UserService.java
> +  }
Este método en particular me hace ruido porque, si tanto la ID del usuario como el token de recuperación son únicos (UUIDs), ¿Por qué no directamente buscar sólo por el token de recuperación? Pregunto para hacer la query lo más específica posible y ahorrarnos el recuperar un dato extra desde el front

2024-09-14 23:40 UTC, EzeSosa commented on src/main/java/com/_up/megastore/services/implementations/UserService.java
> +            + "            <p>If you did not request this change, please ignore this email.</p>\n"
Me encantó esto, buenísimo que lo hayas tenido en cuenta

2024-09-14 23:47 UTC, ValeLattanzi commented on src/main/java/com/_up/megastore/services/implementations/UserService.java
> +    user.setPassword(passwordEncoder.encode(newPassword));
No entiendo por qué validariamos en el back ambas contraseñas.
Porque esa parte de validación la hice en el front, por eso me pareció redundante.

2024-09-15 00:40 UTC, Fedesan14 commented on src/main/java/com/_up/megastore/services/implementations/UserService.java
> +    user.setPassword(passwordEncoder.encode(newPassword));
El servidor nunca debe confiar del frontend, incluso por mas que nosotros seamos los mismos desarrolladores, siempre se hacen las validaciones desde el back ya que este es la que tiene acceso a los datos

2024-09-15 00:57 UTC, EzeSosa commented
Una cosa más @ValeLattanzi, probaste que esto no te tire un 403 desde el back? Lo digo porque en nuestra configuración de endpoints protegidos (https://github.com/7-Seven-Up/megastore-backend/blob/main/src/main/java/com/_up/megastore/security/utils/Endpoints.java) las URL que creaste entrarían en las que están habilitadas sólo para administradores.

Deberías agregar tus URL en el arreglo de las white listed

2024-09-15 01:02 UTC, ValeLattanzi commented
@EzeSosa lo probé todo levantando el Back y el front, pero no me dió ese error. Ahora me pongo a ver eso que me decís de las URL

2024-09-15 02:40 UTC, Fedesan14 commented
> Te dejo esas correcciones que son más que nada detalles, pero me gustó mucho el laburo.
> 
> Unas cositas más:
> 
> 1. Habría que hacer el envío de los correos asíncronos porque demoran mucho el procesamiento de las request. Podríamos hacerlo en esta PR si todos estamos de acuerdo @Fedesan14 @delgadomatias @martinjcrosetto @NicoAntu
> 2. Si tenés un poco más de tiempo para la próxima estaría genial que expliques un poco el flujo de las requests para la recuperación, una descripción cortita
> 
> Good work

Si, coincido que el envío de los emails deberían ser asíncronos, pero podemos hacerlo en otro MR

2024-09-17 22:18 UTC, Fedesan14 requested changes

2024-09-17 22:18 UTC, Fedesan14 commented on src/main/java/com/_up/megastore/controllers/requests/RecoverPasswordRequest.java
> +        String confirmPassword,
Los cambiaria a NotBlank para validar que no se ingrese una contraseña vacia

```suggestion
        @NotBlank(message = "Password must not be null")
        String password,
        @NotBlank(message = "Confirm Password must not be null")
        String confirmPassword,
```

2024-09-17 22:18 UTC, Fedesan14 commented on src/main/java/com/_up/megastore/services/implementations/UserService.java
> +    String recoverPasswordURL = frontendURL + "/auth/recover-password?token=" + user.getRecoverPasswordToken();
Pregunta, esto funciona? No tenes que hacer un .toString() o lo hace solo al querer concatenar dos strings?

```suggestion
    String recoverPasswordURL = frontendURL + "/auth/recover-password?token=" + user.getRecoverPasswordToken().toString();
```

2024-09-17 22:18 UTC, Fedesan14 commented on src/main/java/com/_up/megastore/services/implementations/UserService.java
> +    return userRepository.findByEmailAndDeletedIsFalse(email).orElseThrow(() -> new RuntimeException("User with email " + email +" does not exists."));
Cambiemos este tipo de error a un ResponseStatusException que nos permite además modificar el HTTP Status

```suggestion
    return userRepository.findByEmailAndDeletedIsFalse(email).orElseThrow(() -> new ResponseStatusException(HttpStatus.BAD_REQUEST, "User with email " + email +" does not exists."));
```

2024-09-17 22:18 UTC, Fedesan14 commented on src/main/java/com/_up/megastore/services/implementations/UserService.java
> +    ifTokenIsNotTheSameThrowException(recoverPasswordToken, user);
Los mètodos deberían empezar con un verbo ya que son acciones. Algunas opciones que se me vienen a la mente son

`throwExceptionIfTokenIsNotValid()`
`validateIfTokenIsValid()`

2024-09-17 22:18 UTC, Fedesan14 commented on src/main/java/com/_up/megastore/services/implementations/UserService.java
> +    ifPasswordsAreNotEqualsThrowException(password, confirmPassword);
mismo comentario que recien para estos casos

2024-09-17 22:18 UTC, Fedesan14 commented on src/main/java/com/_up/megastore/services/implementations/UserService.java
> +    return userRepository.findById(userId).orElseThrow(() -> new NoSuchElementException("User with id " + userId + "does not exist"));
Esta [exception](https://docs.oracle.com/javase/8/docs/api/java/util/NoSuchElementException.html) me acabo de dar cuenta que se usa en varios lados, este tipo de exception no representa a lo que realmente queremos decir cuando intentamos encontrar un usuario que no se encuentra sino que es para otra cosa, acceder a los elementos de un iterador por ejemplo.

Para esto mejor usar el ResponseStatusException

```suggestion
    return userRepository.findById(userId).orElseThrow(() -> new ResponseStatusException(HttpStatus.BAD_REQUEST, "User with id " + userId + " does not exist"));
```

Agrego un espacio porque sino va a quedar pegado el userId al "does"

2024-09-18 00:30 UTC, EzeSosa requested changes
Sumo algunos comentarios a la corrección de Fede. Me gustó el flujo de trabajo y cómo resolviste el problema. Good work

2024-09-18 00:30 UTC, EzeSosa commented on src/main/java/com/_up/megastore/services/interfaces/IUserService.java
> +  void recoverPassword(UUID userId, String password, String confirmPassword, UUID recoverPasswordToken);
Ya que tenemos el RecoverPasswordRequest podríamos recibir el objeto completo en vez de sus atributos por separado
```suggestion
  void recoverPassword(UUID userId, RecoverPasswordRequest recoverPasswordRequest);
```

2024-09-18 00:30 UTC, EzeSosa commented on src/main/java/com/_up/megastore/controllers/implementations/UserController.java
>    }
Con lo anterior, esto quedaría más conciso y dejamos al controlador limpio

```suggestion
  public void recoverPassword(UUID userId, RecoverPasswordRequest recoverPasswordRequest) {
    userService.recoverPassword(userId, recoverPasswordRequest);
  }
```

2024-09-18 00:30 UTC, EzeSosa commented on src/main/java/com/_up/megastore/services/implementations/UserService.java
> +    ifTokenIsNotTheSameThrowException(recoverPasswordToken, user);
No banco el segundo nombre, el primero suena mejor

2024-09-18 00:30 UTC, EzeSosa commented on src/main/java/com/_up/megastore/services/implementations/UserService.java
> +  }
Esto podría sacarse de acá y validarse directamente en la request. Dentro de las validaciones de jakarta está la notación @Pattern que te recibe como parámetro una regex

2024-09-18 01:18 UTC, ValeLattanzi commented on src/main/java/com/_up/megastore/services/implementations/UserService.java
> +    String recoverPasswordURL = frontendURL + "/auth/recover-password?token=" + user.getRecoverPasswordToken();
Lo hace solo prácticamente, porque lo probé y no dió ningún problema

2024-09-20 21:38 UTC, Fedesan14 approved these changes

2024-09-21 14:37 UTC, EzeSosa approved these changes

2024-09-24 00:09 UTC, EzeSosa requested changes
Buen laburo en esta PR Latta

2024-09-24 00:09 UTC, EzeSosa commented on src/main/java/com/_up/megastore/controllers/interfaces/IUserController.java
> +  void sendEmailToRecoverPassword(@RequestBody String email);
Poner un @RequestBody como String es bastante complejo, puesto que en la desserialización se agregan algunos caracteres extra. Personalmente crearía un objeto nuevo
```
public record SendRecoverPasswordEmailRequest (
     // Validaciones como @Email 
     String email
)
```
Y lo usaría como body en el método

 ```suggestion
  void sendEmailToRecoverPassword(@RequestBody SendRecoverPasswordEmailRequest sendRecoverEmailPasswordRequest);
```

2024-09-24 15:55 UTC, Fedesan14 approved these changes
Muy buen laburo Latta, te felicito x2!

2024-09-24 15:56 UTC, merged