feat: product name validation
7-Seven-Up/megastore-backend pull request #57
Opened 2024-09-18 19:39 UTC by EzeSosa

Se agregó un método extra dentro del service para validar que el producto que estemos por registrar (o actualizar) no tenga el nombre de otro producto ya existente. 

Por defecto, la implementación de los query methods de JPA (existsBy, findBy) respecto a los strings **no es case sensitive**, esto es, si quiero registrar un producto con el nombre "Camiseta Adidas" pero en la base de datos ya existe un producto con nombre "CAMISETA ADIDAS" se lanzará la excepción. A esto lo dejé así de forma intencional teniendo en cuenta los ejemplos que mostró el profe en clase.

Una interrogante que me surgió sobre esto es **cómo manejar la restauración de productos**. Si nosotros borramos un producto (lógicamente) y luego queremos registrar un nuevo producto que tenga el mismo nombre que el producto borrado, con esta implementación, se lanzará una excepción. Entonces, tenemos dos escenarios:

1. Dejar esta implementación, donde la excepción se lanzará por más que el producto esté borrado, o
2. Permitir registrar (o actualizar) productos cuyo nombre sea igual al de un producto borrado. En este caso, si queremos restaurar ese producto borrado debería lanzarse una excepción indicando que el producto que desea restaurar tiene el mismo nombre que un producto ya existente.

Pienso que la primera implementación nos evita tener registros duplicados en la base de datos pero la segunda quizás sea más cómoda en términos de experiencia de usuario. Me gustaría que a esto lo discutiéramos entre todos @Fedesan14 @delgadomatias @ValeLattanzi @martinjcrosetto @NicoAntu

2024-09-18 21:49 UTC, NicoAntu commented
En mi opinión seria mejor trabajar con la segunda opción, por lo mismo de ser más cómodo en la UX, lo que me entra en duda es si al implementarlo habría algún problema, pero supongo que no seria el caso; no se que diría el resto del equipo.

2024-09-19 00:48 UTC, Fedesan14 requested changes
Te dejo una opción que me parece mejor, esto haría que se tire una excepción si se intenta poner el nombre de un producto ya existe, el unico problema es que no debe saber diferenciar entre mayusculas, es decir

Remera debe ser distinto a remera o ReMera.

Habría que probarlo, en ese caso podriamos ver si hay alguna manera de configurar para que no sea key sensitive o crear una constraint custom.

Sobre el dar de alta un producto con un nombre que ya existe, deberiamos cambiar el deleted a false en el producto que esta almacenado en la base de datos pero deberíamos cambiar los valores a como vengan en la request, ya que podria dar de alta un producto con el nombre Remera, ya existe en base de datos pero a lo mejor el resto de los atributos es diferente al que ya existe en BD

2024-09-19 00:48 UTC, Fedesan14 commented on src/main/java/com/_up/megastore/services/implementations/ProductService.java
> +        throwExceptionIfProductNameAlreadyExists(createProductRequest.name());
Si la idea es evitar tener productos con el mismo nombre, en vez de validar la request mediante una peticion de exists podemos definir una constraint a nivel base de datos para evitar que se puedan almacenar dos productos con el mismo nombre.

Cuando queremos validar cosas de este estilo, como por ejemplo no almacenar productos con el mismo nombre, que el tamaño del nombre sea menor a tantos caracteres, todo estas validaciones deberian hacerse a nivel BD y no solo a nivel DTO.

Este cambio está relacionado con la línea 18 de [`src/main/java/com/_up/megastore/data/model/Product.java`](https://github.com/7-Seven-Up/megastore-backend/blob/main/src/main/java/com/_up/megastore/data/model/Product.java#L18).

```
    @NonNull
    @Column(unique = true)
    private String name;
```

2024-09-19 03:55 UTC, EzeSosa commented
@Fedesan14 Me gusta la idea de incluir una constraint en la base de datos para evitar los nombres duplicados. Con la inclusión de la constraint en la base de datos pensé también en agregar una función capitalizadora para que todos los productos se guarden de forma capitalizada (resolviendo el problema del case sensitive).

> Sobre el dar de alta un producto con un nombre que ya existe, deberiamos cambiar el deleted a false en el producto que esta almacenado en la base de datos pero deberíamos cambiar los valores a como vengan en la request, ya que podria dar de alta un producto con el nombre Remera, ya existe en base de datos pero a lo mejor el resto de los atributos es diferente al que ya existe en BD

El tema es el siguiente: si incluimos esta constraint, ya no va a valer la solución del borrado lógico: al no existir la posibilidad de duplicaciones de registros, por más que el producto esté borrado o no, la excepción se lanzará de igual manera.

Si no, podríamos agregar una constraint personalizada que permita la duplicación únicamente si el producto ya existente está borrado e implementar esa lógica que vos decís, pero para eso sí va a hacer falta hacer una query.

2024-09-19 21:35 UTC, Fedesan14 commented
> @Fedesan14 Me gusta la idea de incluir una constraint en la base de datos para evitar los nombres duplicados. Con la inclusión de la constraint en la base de datos pensé también en agregar una función capitalizadora para que todos los productos se guarden empezando con mayúsculas (resolviendo el problema del case sensitive --todos los nombres se guardan con este formato).
> 
> > Sobre el dar de alta un producto con un nombre que ya existe, deberiamos cambiar el deleted a false en el producto que esta almacenado en la base de datos pero deberíamos cambiar los valores a como vengan en la request, ya que podria dar de alta un producto con el nombre Remera, ya existe en base de datos pero a lo mejor el resto de los atributos es diferente al que ya existe en BD
> 
> El tema es el siguiente: si incluimos la constraint que mencioné, ya no va a valer la solución del borrado lógico: al no existir la posibilidad de duplicaciones de registros, por más que el producto esté borrado o no, la excepción se lanzará de igual manera.
> 
> Si no, podríamos agregar una constraint personalizada que permita la duplicación únicamente si el producto ya existente está borrado e implementar esa lógica que vos decís, pero para eso sí va a hacer falta hacer una query.

El problema de la funcion capilaizadora, es que si el usuario escribe el nombre como "Remera" vos la vas a almacenas como "REMERA" o "remera", el problema de esto es que cuando quieras obtener el producto no lo vas a hacer con el nombre que realmente guardó el usuario y está mal.

La verdad es que a mi nunca me gustó el borrado lógico porque no tiene sentido en la mayoria de los casos y aparecen problemas como este que mencionás, en algunos casos muy en particular es que realmente merece la pena un borrado lógico. 

Me interesa lo de la constraint personalizada

2024-09-20 04:33 UTC, EzeSosa commented
> Me interesa lo de la constraint personalizada
@Fedesan14 Ahí implementé la constraint. Como había mencionado, se debe utilizar una query y la solución que planteé realiza las validaciones a nivel DTO (mismo escenario que el número de teléfono en el registrar usuario). Más allá de que implementar la constraint a nivel base de datos no es posible por el borrado lógico, esta solución tiene otra ventaja importante, y es que nos evitamos subir imágenes innecesarias a Cloudinary.

Con el escenario de la constraint en la BD, era posible que ocurriese la siguiente situación:

1. Se validan todos los atributos del DTO del producto
2. Se suben las imágenes a Cloudinary y se guardan en la BD
3. Al intentar guardar el nombre en la BD la constraint lanza el error
4. Las imágenes se borran de la base de datos ya que estamos utilizando el bendito @Transactional, pero las imágenes ya fueron subidas a Cloudinary

Además, con esta solución, es posible registrar un producto cuyo nombre coincida con otro producto que está eliminado, y, al intentar restaurar este último, se lanzará una excepción indicando que el producto no se puede restaurar porque ya existe otro con ese nombre.

> Sobre el dar de alta un producto con un nombre que ya existe, deberiamos cambiar el deleted a false en el producto que esta almacenado en la base de datos pero deberíamos cambiar los valores a como vengan en la request, ya que podria dar de alta un producto con el nombre Remera, ya existe en base de datos pero a lo mejor el resto de los atributos es diferente al que ya existe en BD

Esto me parece bastante bueno pero lo dejaría para otra MR

2024-09-20 14:44 UTC, Fedesan14 requested changes

2024-09-20 14:44 UTC, Fedesan14 commented on src/main/java/com/_up/megastore/data/repositories/IProductRepository.java
> +    boolean existsByNameAndDeletedIsFalse(String name);
Agregaria el IgnoreCase para que salte error si se quiera guardar "REMERA" y ya existe "Remera"

```suggestion
    boolean existsByNameIgnoreCaseAndDeletedIsFalse(String name);
```

2024-09-20 15:10 UTC, Fedesan14 approved these changes

2024-09-21 14:19 UTC, ValeLattanzi approved these changes
Me gusta lo de haber creado una anotación para validar el nombre del producto

2024-09-21 15:06 UTC, merged