feat: category name validation
7-Seven-Up/megastore-backend pull request #58
Opened 2024-09-18 23:31 UTC by NicoAntu

added an extra method in the category service to validate if you register or update a category doesn'thave the name of another already registered

2024-09-25 02:46 UTC, Fedesan14 requested changes

2024-09-25 02:46 UTC, Fedesan14 commented on src/main/java/com/_up/megastore/data/repositories/ICategoryRepository.java
> -    boolean existsByName(String name);
Ojo con eliminar este método, no se usa para ninguna otra cosa? Quizás estás afectando al funcionamiento de otra feature. Fijate que no se use, en caso de usarlo para algo, la mejor opcion es solamente crear el nuevo metodo existsByNameAndDeletedIsFalse y dejar tambien este existsByName

2024-09-25 14:54 UTC, EzeSosa approved these changes

2024-09-25 22:21 UTC, NicoAntu commented on src/main/java/com/_up/megastore/data/repositories/ICategoryRepository.java
> -    boolean existsByName(String name);
Me fije en el código y no se utiliza el existsByName en otra feature de la categoría, además de que el compilador no tiro ningún error.

2024-09-27 01:57 UTC, Fedesan14 approved these changes

2024-09-27 01:57 UTC, merged