feat: size name validation
7-Seven-Up/megastore-backend pull request #59
Opened 2024-09-18 23:34 UTC by NicoAntu

added an extra method in the size service to validate if you register or update a size doesn't have the name of another already registered

2024-09-25 02:47 UTC, Fedesan14 requested changes

2024-09-25 02:47 UTC, Fedesan14 commented on src/main/java/com/_up/megastore/data/repositories/ISizeRepository.java
> -    boolean existsByName(String name);
Mismo comentario que deje en el otro MR, verifiquemos que este existsByName no se esté utilizando para nada, en caso de no usarse lo eliminamos, en caso de usarse dejamos ambos métodos

2024-09-25 14:53 UTC, EzeSosa approved these changes

2024-09-25 22:26 UTC, NicoAntu commented on src/main/java/com/_up/megastore/data/repositories/ISizeRepository.java
> -    boolean existsByName(String name);
Igual que el otro MR, revisado que no se utiliza el método y el compilador tira que no hay errores.

2024-09-27 02:06 UTC, Fedesan14 approved these changes

2024-09-27 02:06 UTC, merged