feat: expire-account-activation
7-Seven-Up/megastore-backend pull request #60
Opened 2024-09-19 03:05 UTC by martinjcrosetto

Se realizó la expiración del token de la activación de cuenta que se crea una vez el usuario se guarda en la base de datos.

1. User.Java:
    -Se modifico el atributo activationToken, eliminando la palabra final. Esto permitirá asignarle un token al guardar el usuario, o reasignarlo en caso de que el token haya expirado. Esto es para debatir, porque una vez se registra el usuario, su email asociado queda guardado, entonces de ahí a que elimine el final para regenerar el token.
    -Se agregó un atributo tokenExpirationDate de tipo localtime
2. UserService
    -saveUser: se agregó una llamada al método generateActivationToken, que permitirá generar y asignar al usuario tanto el 
     activationToken como el tokenExpirationDate con un tiempo de expiracion de 24 horas a partir de su generación.
    -activateUser: se agregó una validación para determinar si el activationToken está expirado., de ser este el caso se lanzará una 
     excepción.

2024-09-19 18:48 UTC, EzeSosa requested changes
Buen laburo Crous. Te dejo estas correcciones sobre cómo guardar los datos. Me gustó que en la PR sólo te hayas enfocado en la expiración; la generación de nuevos tokens la dejamos para otra

2024-09-23 15:19 UTC, EzeSosa requested changes
En general, pienso que como ahora tenemos una clase Token con su propio id y que está asociada a un user apenas se crea, ya no es necesario el parámetro userId al momento de realizar las búsquedas. Creo que a esto lo habíamos hablado en la PR de Latta.

Te recomendaría que crees un TokenRepository y que uses los query methods en vez de filtrar en memoria, es mejor práctica y mucho más rápido.

2024-09-23 15:19 UTC, EzeSosa commented on src/main/java/com/_up/megastore/services/implementations/UserService.java
> +    activationToken.setUser(user);
Ya que venimos creando objetos con el Builder pattern podríamos implementarlo también acá
```suggestion
    Token.builder() // El ID se podría generar automáticamente a nivel model
         .user(user)
         .build();
```

2024-09-23 15:19 UTC, EzeSosa commented on src/main/java/com/_up/megastore/data/model/Token.java
> +    private UUID activationToken;
Banco que la propia ID sea el token de activación. Ya que vamos a asignar un randomUUID() podríamos hacerlo directamente acá (y agregarle el final, por supuesto)
```suggestion
    private final UUID tokenId = UUID.randomUUID();
```

2024-09-23 15:19 UTC, EzeSosa commented on src/main/java/com/_up/megastore/services/implementations/UserService.java
> +    user.setActivationTokens(activationTokens);
No estoy seguro sobre esto pero creo que se podría simplificar
```suggestion
    user.getActivationTokens().add(activationToken);
```
Tengo entendido que, como la lista es la misma instancia mutable que está asociada al objeto user, debería actualizarse sólo con el add

2024-09-23 15:19 UTC, EzeSosa commented on src/main/java/com/_up/megastore/services/implementations/UserService.java
> +            .orElseThrow(() -> new NoSuchElementException());
Hacer las queries directamente a la base de datos es más rápido que filtrar en memoria. Además, el encontrar el token por su ID debería ser responsabilidad de su repositorio correspondiente. Sugiero crear la siguiente clase:

``
public interface ITokenRepository extends JpaRepository<Token, UUID> {
}
``

Eso ya te proporciona un método para buscar el token por su id

2024-09-23 15:19 UTC, EzeSosa commented on src/main/java/com/_up/megastore/services/implementations/UserService.java
> +    return userRepository.findByUserIdAndActivatedIsFalse(userId).filter(user -> user.getActivationTokens().stream().anyMatch( activationToken-> activationToken.getActivationToken().equals(activation
Acá no banco. Podríamos mover este método al repositorio de Tokens para que nos devuelva el user asociado a ese token (o, de última, buscar ese token por su ID y devolver el user asociado con un .getUser())

2024-09-23 15:23 UTC, martinjcrosetto commented on src/main/java/com/_up/megastore/data/model/Token.java
> +    private UUID activationToken;
En este caso, ¿cómo sería luego con la renovación de nuevos tokens?, crearíamos otro objeto o actualizaríamos su UUID, porque en el segundo caso, no podríamos si usamos final.

2024-09-23 15:52 UTC, Fedesan14 commented on src/main/java/com/_up/megastore/data/model/Token.java
> +    private UUID activationToken;
Se debería generar un nuevo token

2024-09-23 17:58 UTC, Fedesan14 requested changes

2024-09-23 17:58 UTC, Fedesan14 commented on src/main/java/com/_up/megastore/services/implementations/UserService.java
> +            .build();
O llamamos al constructor o llamamos al builder

```suggestion
    Token activationToken =    activationToken.builder()
            .user(user)
            .build();

```

Ambas cosas tienen el mismo objetivo

2024-09-23 17:58 UTC, Fedesan14 commented on src/main/java/com/_up/megastore/services/implementations/UserService.java
> +        + user.getUserId() + "&activationToken=" + findActivationTokenByTokenUUIDOrThrowException(activationToken).getTokenId();
Si lo acabamos de generar, por qué lo vamos a buscar a la BD?

```suggestion
        + user.getUserId() + "&activationToken=" + activationToken;
```

2024-09-23 17:58 UTC, Fedesan14 commented on src/main/java/com/_up/megastore/data/model/Token.java
> +    @ManyToOne
Hace falta que hagamos una relación bidireccional? Creo que la unica dirección que vale la pena la relacion es user -> tokens

2024-09-23 17:58 UTC, Fedesan14 commented on src/main/java/com/_up/megastore/services/implementations/UserService.java
> +            .orElseThrow(() -> new NoSuchElementException("User with username " + username + " does not exist."));
Cambiemos el tipo de exception a este

```suggestion
            .orElseThrow(() -> new ResponseStatusException(HttpStatus.BAD_REQUEST, "User with username " + username + " does not exist."));
```

2024-09-23 17:58 UTC, Fedesan14 commented on src/main/java/com/_up/megastore/services/implementations/UserService.java
> +      throw new IllegalArgumentException("Token has expired");
Acá lo mismo
```suggestion
      throw new ResponseStatusException(HttpStatus.BAD_REQUEST, "Token has expired");
```

2024-09-23 21:30 UTC, EzeSosa requested changes
Habría que cambiar luego la ruta de activación del usuario. Ya que ahora tenemos un token, podríamos realizar las búsquedas sólo por ese token y evitar mostrar el id del usuario. De todos modos lo dejaría para otra PR

2024-09-23 21:30 UTC, EzeSosa commented on src/main/java/com/_up/megastore/data/repositories/ITokenRepository.java
> +    Optional<Token> findByTokenId(UUID tokenId);
Esto no hace falta, ya te lo proporciona JPA por defecto. El método es el siguiente
`
Optional<Token> findById(UUID id)
`

2024-09-23 21:30 UTC, EzeSosa commented on src/main/java/com/_up/megastore/services/implementations/UserService.java
>              .orElseThrow(() -> new NoSuchElementException());
Acá también podríamos cambiar la excepción a ResponseStatus como en las otras correcciones

2024-09-26 04:20 UTC, ValeLattanzi approved these changes
Muy buen trabajo Crous, ninguna devolución para hacer. 
Súbete a la bici y caete! 🛒

2024-09-26 05:59 UTC, EzeSosa requested changes
Te dejo un par de correcciones relacionadas a los principios SOLID y a cómo ahora vamos a buscar los tokens. La verdad esta PR se complicó bastante, yo pensé que era más simple. Si necesitás una mano no dudes en llamarme que estamos prácticamente en una deadline

PD: se me pasó porque la verdad no había entendido qué era, pero borrá ese archivo 'a' por favor jajaja

2024-09-26 05:59 UTC, EzeSosa commented on src/main/java/com/_up/megastore/services/implementations/TokenService.java
> +    }
1. Cambiémosle el nombre a algo más descriptivo
2. Está mal que hagas un findById(id).get() porque, ¿Qué pasa si el usuario nos mete un token alterado? El user asociado a ese token no se va a encontrar. Habría que manejar eso con un .orElseThrow()
3. ¿Por qué devolvemos el ID y no el user?

```suggestion
    public UUID findUserByActivationToken(UUID activationTokenId) {
        return iTokenRepository.findById(activationToken)
             .orElseThrow(() -> new ResponseStatusException(HttpStatus.BAD_REQUEST, "Token with ID " + activationTokenId + " does not exist.")
             .getUser();
    }
```

2024-09-26 05:59 UTC, EzeSosa commented on src/main/java/com/_up/megastore/services/implementations/UserService.java
>    }
Con lo anterior esto se solucionaría. Acá estás (1) buscando la ID del usuario que ya buscaste previamente y (2) buscando ese mismo usuario por la id. Son dos consultas iguales a la base de datos. Cambiémoslo por esto
```suggestion
  private User findUserToActivateOrThrowException(UUID activationTokenUUID) {
    return tokenService.findUserByActivationToken(activationTokenUUID); 
    // A la excepción la manejás en el token service
  }
```

2024-09-26 05:59 UTC, EzeSosa commented on src/main/java/com/_up/megastore/services/implementations/UserService.java
> +  }
Esto NO debe estar acá. Buscar un token por su ID no es responsabilidad del user service, sino responsabilidad del **token service**. Movamos este método a donde corresponde

2024-09-26 05:59 UTC, EzeSosa commented on src/main/java/com/_up/megastore/services/implementations/UserService.java
>    private final ITokenRepository tokenRepository;
Con lo anterior te ahorrás inyectar el bean de un repositorio que no corresponde a este servicio

2024-09-26 05:59 UTC, EzeSosa commented on src/main/resources/application.yaml
> +    password: ${DB_PASSWORD:martin1234}
:angry:

2024-09-26 05:59 UTC, EzeSosa commented on src/main/java/com/_up/megastore/services/implementations/UserService.java
>    private Boolean isTokenExpired(UUID activationTokenUUID){
A este método también lo vamos a tener que cambiar para que busque el token en el token service y no acá

2024-09-26 05:59 UTC, EzeSosa commented on src/main/java/com/_up/megastore/services/implementations/UserService.java
> +  }
A esto también lo vas a tener que modificar. Este método supone que el recoverPasswordToken está dentro de la entity User cuando es una clase aparte. Nuevamente, vas a tener que reciclar el findTokenById del token service

2024-09-26 05:59 UTC, EzeSosa commented on src/main/java/com/_up/megastore/services/implementations/UserService.java
> +      IEmailService emailService, ITokenRepository tokenRepository, ITokenService iTokenService) {
Usemos los nombres apropiados
```suggestion
      IEmailService emailService, ITokenRepository tokenRepository, ITokenService tokenService) {
```

2024-09-26 05:59 UTC, EzeSosa commented on src/main/java/com/_up/megastore/services/implementations/UserService.java
> +    this.tokenService = iTokenService;
Lo mismo acá
```suggestion
    this.tokenService = tokenService;
```

2024-09-26 14:14 UTC, martinjcrosetto commented on src/main/java/com/_up/megastore/services/implementations/TokenService.java
> +    }
Devolvemos el ID y no el user para que despues validemos mediante un query method, encontrar el user si y solo si el user no esta activado

2024-09-26 17:17 UTC, EzeSosa commented on src/main/java/com/_up/megastore/services/implementations/TokenService.java
> +                .orElseThrow(() -> new ResponseStatusException(HttpStatus.BAD_REQUEST, "Token with UUID " + token + " does not exist."));
No te repitas
```suggestion
    @Override
    public User findUserByActivationToken(UUID activationToken){
        Token token = findTokenByIdOrThrowException(activationToken);
        return token.getUser();
    }

    @Override
    public Token findTokenByIdOrThrowException(UUID token){
        return iTokenRepository.findById(token)
                .orElseThrow(() -> new ResponseStatusException(HttpStatus.BAD_REQUEST, "Token with UUID " + token + " does not exist."));
```

2024-09-26 17:18 UTC, EzeSosa commented on src/main/java/com/_up/megastore/services/implementations/UserService.java
> +      IEmailService emailService, ITokenService TokenService) {
Normalmente no te lo corregiría pero ya que vas a hacer otro commit lo hago. Estamos declarando las variables en **camel case**
```suggestion
      IEmailService emailService, ITokenService tokenService) {
```

2024-09-26 17:18 UTC, EzeSosa commented on src/main/java/com/_up/megastore/services/implementations/UserService.java
> +    this.tokenService = TokenService;
Lo mismo
```suggestion
    this.tokenService = tokenService;
```

2024-09-26 17:19 UTC, EzeSosa commented on src/main/java/com/_up/megastore/services/implementations/UserService.java
> +    }
Movámoslo a un método privado
```suggestion
    throwExceptionIfUserIsActivated(User user);
```
```
private void throwExceptionIfUserIsActivated(User user) {
    if (user.isActivated()) {
      throw new IllegalArgumentException("User with UUID " + user.getUserId() + " is already activated.");
    }
}
```

2024-09-26 20:04 UTC, EzeSosa approved these changes

2024-09-27 02:05 UTC, Fedesan14 approved these changes

2024-09-27 02:45 UTC, merged