fix: name updates
7-Seven-Up/megastore-backend pull request #85
Opened 2024-09-29 23:43 UTC by EzeSosa

Se arregló el problema que había al actualizar algún otro atributo distinto al nombre de un producto/categoría/tamaño. El problema estaba en las constraints que utilizábamos, que no validaba que el nombre que ingresamos en la actualización sea distinto al del objeto ya existente.

En esta misma PR se arregló este error que estaba replicado en productos, tamaños y categorías. Dado el corto tiempo, incluí las tres cuestiones en esta misma PR.

2024-09-29 23:56 UTC, Fedesan14 requested changes

2024-09-29 23:56 UTC, Fedesan14 commented on src/main/java/com/_up/megastore/services/implementations/ProductService.java
> +    }
Esto al final no lo vamos a hacer ya que podrian existir dos productos "Samsung S24" (por ejemplo)

2024-09-30 00:05 UTC, EzeSosa commented on src/main/java/com/_up/megastore/services/implementations/ProductService.java
> +    }
Oki

2024-09-30 00:19 UTC, Fedesan14 approved these changes

2024-09-30 00:19 UTC, merged