feat: finish order
7-Seven-Up/megastore-backend pull request #99
Opened 2024-10-24 18:54 UTC by EzeSosa

Se implementó la funcionalidad para cambiar una orden de estado 'en progreso' a 'finalizada'. Acorde a nuestra seguridad, el endpoint está autorizado únicamente para **administradores**. Además, se realizó un poco de refactoreo en el OrderService y en el OrderMapper para hacer menos rígida la OrderResponse. 

Una vez las órdenes son actualizadas, se le envía un correo electrónico al cliente avisándole de este cambio de estado y pasándole también el link para que pueda consultar su pedido (si la URL del front no es correcta, esto se cambia).

## Tests

Para los tests, se hicieron, nuevamente, dos test de integración acorde a la documentación en Notion sobre los test de transición de estados. Se testea que una orden en estado IN_PROGRESS pase a FINISHED, y posteriormente se testea que una orden que no esté en estado IN_PROGRESS no pueda pasar a FINISHED.

El envío de correos, obviamente, fue mockeado.

2024-10-25 19:19 UTC, ValeLattanzi approved these changes

2024-10-25 22:30 UTC, Fedesan14 requested changes

2024-10-25 22:30 UTC, Fedesan14 commented on src/main/java/com/_up/megastore/controllers/interfaces/IOrderController.java
> +    @ResponseStatus(HttpStatus.CREATED)
Deberia ser un OK, ya que no se crea una orden sino que se cambia su estado luego de cometer una accion en particular


```suggestion
    @ResponseStatus(HttpStatus.OK)
```

2024-10-25 22:30 UTC, Fedesan14 commented on src/main/java/com/_up/megastore/services/implementations/OrderService.java
> +                .orElseThrow(() -> new ResponseStatusException(HttpStatus.BAD_REQUEST, "Order with id " + orderId + " does not exist."));
Ojo con esto que no vaya a mostrarse el ID en el front, o cambiamos el mensaje o el front modifica el mensaje

2024-10-25 22:30 UTC, Fedesan14 commented on src/main/java/com/_up/megastore/services/implementations/OrderService.java
> +        throwExceptionIfStateIsNotInProgress(order);
Excelente esta validación

2024-10-25 22:30 UTC, Fedesan14 commented on src/main/java/com/_up/megastore/services/implementations/OrderService.java
>      }
Podemos usar la funcion SUM de SQL para no tener que hacer esto en memoria, la base de datos debería hacerlo más rápido. Incluso, podríamos guardar el subtotal en cada detalle para que luego hagamos SUM de los subtotales, sin tener que multiplicarlo por la cantidad en la consulta

2024-10-25 22:30 UTC, Fedesan14 commented on src/main/java/com/_up/megastore/services/implementations/OrderService.java
> +            throw new ResponseStatusException(HttpStatus.BAD_REQUEST, "Order with id " + order.getOrderId() + " is not in progress.");
Mismo mensaje que antes, ojo que no mostremos el ID de la orden, en este caso podriamos quizás mostrar el numero de orden ,ya que éste es único y si lo conoce el usuario

2024-10-25 23:45 UTC, EzeSosa commented
@Fedesan14 ahí cambié el model para guardar directamente el subtotal en OrderDetail. Agregué también un test para verificarlo cuando creamos el pedido

2024-10-26 01:13 UTC, Fedesan14 approved these changes

2024-10-26 01:14 UTC, merged